# Introduction {#intro}

This document overviews the data availability of household consumption surveys and challenges for poverty measurement in the region of South Asia. The starting point in monitoring progress in poverty reduction and enhancing shared prosperity in the region is to have household consumption survey data that are not only available at reasonably frequent intervals, but are also comparable over time (Serajuddin, Uematsu,
Wieser, Yoshida, & Dabalen, 2015). 

Cost of living adjustments and a consumer price index (CPI) are also necessary to count the poor across countries using a common currency and a global poverty line. At present, data on purchasing power parity (PPP) comes from the International Comparison Program (ICP) collected in 2011, which is absent for Afghanistan. 

The World Bank set a target of reducing extreme poverty to less than 3 percent by 2030 and to ensure continued focus and steady progress toward the goal, the institution set an interim target of 9 percent by 2020. Progress towards this goal is measured by monitoring the share of the global population living below the international poverty line, currently set at US$1.90 in 2011 purchasing power parity (PPP) dollars. All eight countries in South Asia measure the international extreme poverty status of an individual by comparing consumption per capita against this poverty line. According to the Poverty and Shared Prosperity Report 2018, Nigeria may already have overtaken India as the country with the most extreme poor in the world. Still, to achieve the global poverty goal, progress in poverty reduction needs to continue in India and the rest of South Asia. Despite a poverty rate of 13.4 percent, India’s large population of 1.3 billion results in a high absolute number of poor (approximately 170 million poor people in 2015). 

In the South Asia region, four out of five extreme poor reside in India. Bangladesh has made remarkable progress in reducing poverty, but its large population still maintains it in second place within the region in terms of absolute number of poor. Sri Lanka is considered a development success story where extreme poverty has become rare, although a large share of the population subsists on slightly more than the extreme poverty line. Bhutan has also been successful in reducing poverty. 

Even as much of the region leaves extreme poverty behind, poverty is becoming more entrenched and harder to root out in certain areas, particularly in countries burdened by violent conflict and weak institutions. Nepal experienced devastating earthquakes in 2015 and the Maldives were devastated by the 2004 tsunami while its tourism industry is seriously threatened by climate change. In the case of Afghanistan, poverty is increasing as violence continues to affect the security of livelihoods and economic activity in the country. 

These guidelines are organized as follows. Chapter 1 presents the metadata analysis, which may be broadly described as an overview of the household survey questionnaires. This section studies the household surveys’ raw data, sampling methodology, coverage, data capturing methods, and ability to measure food, non-food, durables, and housing expenditures. Chapter 2 presents the harmonized data from the South Asia Micro Database (SARMD) with a series of quality checks to verify that each harmonized variable has been constructed properly. Two kinds of quality checks of the harmonized data have been conducted. A static quality check evaluates whether the harmonized variables are present and whether there is a high percentage of missing values. It also delves deeper into variables that may be interrelated with other variables. For example, a high percentage of households that have access to a television, but do not have access to electricity may raise questions on how these variables were constructed. A dynamic quality check evaluates the inconsistencies in measurement of harmonized data over time. It provides a better overview on whether categorical variables have changed over time and provides poverty and inequality measures. Chapter 3 presents three analytical notes that have resulted from the analysis. 
