# (PART) Metadata Analysis of Raw data {-}

# Introduction to metadata analysis {#metadata .unnumbered}
***

>From the archivist's and the end user's perspective, a ‘good’ dataset is one that is easy to use. Its documentation is clear and easy to understand, the data contains no surprises, and users are able to access the dataset with relatively little start-up time [@inter-university_consortium_for_political_and_social_research_icpsr_guide_2012]. 

The second part of this book studies the available metadata for household surveys in SARMD. Metadata is documentation that describes data and, though it may take many different forms, it must meet certain objectives such as helping the user find the data they are interested in, understand what the data are measuring and how the data have been created, and assess the quality of the data. In addition, good metadata should also reduce the burden of the data producer/maintainer, as it reduces the need to provide regular support to users of the data [@ihsn_microdata_2014]. 

This part contains two chapters:

**Chapter 4** focuses on survey availability to present precisely which surveys are available where and when. 

**Chapter 5** goes deeper into the survey questionnaires to compare the information collected by the surveys in relation to the four main expenditure components: food, non-food, durables, and rent. 

