<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Chapter 1 Metadata overview | South Asia Micro Database (SARMD) User Guidelines</title>
  <meta name="description" content="SARMD User Guidelines">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Chapter 1 Metadata overview | South Asia Micro Database (SARMD) User Guidelines" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="SARMD User Guidelines" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 1 Metadata overview | South Asia Micro Database (SARMD) User Guidelines" />
  
  <meta name="twitter:description" content="SARMD User Guidelines" />
  

<meta name="author" content="South Asia Region Team for Statistical Development (SARTSD)">


<meta name="date" content="2019-03-13">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="introduction-to-south-asia.html">
<link rel="next" href="qcheck.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">SARMD User Guidelines</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="" data-path="content.html"><a href="content.html"><i class="fa fa-check"></i>Content</a></li>
<li class="chapter" data-level="" data-path="introduction-to-south-asia.html"><a href="introduction-to-south-asia.html"><i class="fa fa-check"></i>Introduction to South Asia</a><ul>
<li class="chapter" data-level="" data-path="introduction-to-south-asia.html"><a href="introduction-to-south-asia.html#poverty-measurement"><i class="fa fa-check"></i>Poverty measurement</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="metadata.html"><a href="metadata.html"><i class="fa fa-check"></i><b>1</b> Metadata overview</a><ul>
<li class="chapter" data-level="1.1" data-path="metadata.html"><a href="metadata.html#inventory"><i class="fa fa-check"></i><b>1.1</b> Inventory</a></li>
<li class="chapter" data-level="1.2" data-path="metadata.html"><a href="metadata.html#household-survey-description-by-country"><i class="fa fa-check"></i><b>1.2</b> Household survey description by country</a><ul>
<li class="chapter" data-level="1.2.1" data-path="metadata.html"><a href="metadata.html#afghanistan"><i class="fa fa-check"></i><b>1.2.1</b> Afghanistan</a></li>
<li class="chapter" data-level="1.2.2" data-path="metadata.html"><a href="metadata.html#bangladesh"><i class="fa fa-check"></i><b>1.2.2</b> Bangladesh</a></li>
<li class="chapter" data-level="1.2.3" data-path="metadata.html"><a href="metadata.html#bhutan"><i class="fa fa-check"></i><b>1.2.3</b> Bhutan</a></li>
<li class="chapter" data-level="1.2.4" data-path="metadata.html"><a href="metadata.html#india"><i class="fa fa-check"></i><b>1.2.4</b> India</a></li>
<li class="chapter" data-level="1.2.5" data-path="metadata.html"><a href="metadata.html#maldives"><i class="fa fa-check"></i><b>1.2.5</b> Maldives</a></li>
<li class="chapter" data-level="1.2.6" data-path="metadata.html"><a href="metadata.html#nepal"><i class="fa fa-check"></i><b>1.2.6</b> Nepal</a></li>
<li class="chapter" data-level="1.2.7" data-path="metadata.html"><a href="metadata.html#pakistan"><i class="fa fa-check"></i><b>1.2.7</b> Pakistan</a></li>
<li class="chapter" data-level="1.2.8" data-path="metadata.html"><a href="metadata.html#sri-lanka"><i class="fa fa-check"></i><b>1.2.8</b> Sri Lanka</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="metadata.html"><a href="metadata.html#sample-size"><i class="fa fa-check"></i><b>1.3</b> Sample size</a></li>
<li class="chapter" data-level="1.4" data-path="metadata.html"><a href="metadata.html#expenditure-components"><i class="fa fa-check"></i><b>1.4</b> Expenditure components</a><ul>
<li class="chapter" data-level="1.4.1" data-path="metadata.html"><a href="metadata.html#food"><i class="fa fa-check"></i><b>1.4.1</b> Food</a></li>
<li class="chapter" data-level="1.4.2" data-path="metadata.html"><a href="metadata.html#non-food"><i class="fa fa-check"></i><b>1.4.2</b> Non-food</a></li>
<li class="chapter" data-level="1.4.3" data-path="metadata.html"><a href="metadata.html#durable-assets"><i class="fa fa-check"></i><b>1.4.3</b> Durable assets</a></li>
<li class="chapter" data-level="1.4.4" data-path="metadata.html"><a href="metadata.html#housing"><i class="fa fa-check"></i><b>1.4.4</b> Housing</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="qcheck.html"><a href="qcheck.html"><i class="fa fa-check"></i><b>2</b> Harmonized data quality check</a><ul>
<li class="chapter" data-level="2.1" data-path="qcheck.html"><a href="qcheck.html#basic-survey-characteristics"><i class="fa fa-check"></i><b>2.1</b> Basic survey characteristics</a></li>
<li class="chapter" data-level="2.2" data-path="qcheck.html"><a href="qcheck.html#demographics"><i class="fa fa-check"></i><b>2.2</b> Demographics</a></li>
<li class="chapter" data-level="2.3" data-path="qcheck.html"><a href="qcheck.html#education"><i class="fa fa-check"></i><b>2.3</b> Education</a></li>
<li class="chapter" data-level="2.4" data-path="qcheck.html"><a href="qcheck.html#durable-assets-1"><i class="fa fa-check"></i><b>2.4</b> Durable assets</a></li>
<li class="chapter" data-level="2.5" data-path="qcheck.html"><a href="qcheck.html#housing-1"><i class="fa fa-check"></i><b>2.5</b> Housing</a></li>
<li class="chapter" data-level="2.6" data-path="qcheck.html"><a href="qcheck.html#labor"><i class="fa fa-check"></i><b>2.6</b> Labor</a></li>
<li class="chapter" data-level="2.7" data-path="qcheck.html"><a href="qcheck.html#poverty"><i class="fa fa-check"></i><b>2.7</b> Poverty</a></li>
<li class="chapter" data-level="2.8" data-path="qcheck.html"><a href="qcheck.html#inequality"><i class="fa fa-check"></i><b>2.8</b> Inequality</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="application.html"><a href="application.html"><i class="fa fa-check"></i><b>3</b> Analytical notes</a><ul>
<li class="chapter" data-level="3.1" data-path="application.html"><a href="application.html#nonlinear-relationship-between-expenditure-and-asset-acquisition"><i class="fa fa-check"></i><b>3.1</b> Nonlinear relationship between expenditure and asset acquisition</a></li>
<li class="chapter" data-level="3.2" data-path="application.html"><a href="application.html#household-composition-and-poverty"><i class="fa fa-check"></i><b>3.2</b> Household composition and poverty</a></li>
<li class="chapter" data-level="3.3" data-path="application.html"><a href="application.html#gender-equality-in-education"><i class="fa fa-check"></i><b>3.3</b> Gender equality in education</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">South Asia Micro Database (SARMD) User Guidelines</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="metadata" class="section level1">
<h1><span class="header-section-number">Chapter 1</span> Metadata overview</h1>
<p>This chapter provides an overview of household surveys metadata in SAR and MNA with the support of a series of accompanying Tableau dynamic dashboards.</p>
<p>The South Asia Micro Database (SARMD) is a regional database of socio-economic indicators established in 2014 and managed by the South Asia Region Team for Statistical Development (SARTSD). It follows the Global Monitoring Database (GMD) harmonization guidelines, including the construction of the welfare aggregate used for global poverty monitoring. SARMD consists of raw household survey data, documentation, questionnaires, and a repository of do files to reconstruct harmonized variables, consumption aggregates, and poverty estimates. SARMD currently includes the eight countries in the region, contemplates forty-three surveys, and contains close to a hundred harmonized variables covering the 1993-2017 period. Table <a href="metadata.html#tab:latest">1.1</a> shows the latest available household surveys in SARMD.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(readr)</code></pre></div>
<pre><code>## Warning: package &#39;readr&#39; was built under R version 3.5.2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">latest &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;~/SARMD_User_Guidelines/SARMD_guidelines/tables/latest.csv&quot;</span>)</code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   Country = col_character(),
##   `Name of the survey` = col_character(),
##   `National Statistics Office` = col_character(),
##   `Sample size: Number of households` = col_number()
## )</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">knitr::<span class="kw">kable</span>(latest,<span class="dt">booktabs=</span><span class="ot">TRUE</span>, <span class="dt">caption =</span> <span class="st">&#39;Latest household surveys available in SARMD&#39;</span>)</code></pre></div>
<table>
<caption><span id="tab:latest">Table 1.1: </span>Latest household surveys available in SARMD</caption>
<thead>
<tr class="header">
<th align="left">Country</th>
<th align="left">Name of the survey</th>
<th align="left">National Statistics Office</th>
<th align="right">Sample size: Number of households</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Afghanistan, 2016</td>
<td align="left">Living Conditions Survey</td>
<td align="left">Central Statistics Organization</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">Bangladesh, 2016</td>
<td align="left">Household Income and Expenditure Survey</td>
<td align="left">Bangladesh Bureau of Statistics</td>
<td align="right">46068</td>
</tr>
<tr class="odd">
<td align="left">Bhutan, 2017</td>
<td align="left">Living Standards Survey</td>
<td align="left">National Statistics Bureau</td>
<td align="right">11396</td>
</tr>
<tr class="even">
<td align="left">India, 2017</td>
<td align="left">National Sample Survey</td>
<td align="left">Ministry of Statistics and Programme Implementation</td>
<td align="right">NA</td>
</tr>
<tr class="odd">
<td align="left">Maldives, 2016</td>
<td align="left">Household Income and Expenditure Survey</td>
<td align="left">National Bureau of Statistics</td>
<td align="right">4910</td>
</tr>
<tr class="even">
<td align="left">Nepal, 2016</td>
<td align="left">Annual Household Survey</td>
<td align="left">Central Bureau of Statistics</td>
<td align="right">4500</td>
</tr>
<tr class="odd">
<td align="left">Pakistan, 2015</td>
<td align="left">Social and Living Standards Measurement Survey</td>
<td align="left">Pakistan Bureau of Statistics</td>
<td align="right">24238</td>
</tr>
<tr class="even">
<td align="left">Sri Lanka, 2016</td>
<td align="left">Household Income and Expenditure Survey</td>
<td align="left">Department of Census and Statistics</td>
<td align="right">21756</td>
</tr>
</tbody>
</table>
<div id="inventory" class="section level2">
<h2><span class="header-section-number">1.1</span> Inventory</h2>
<p>Considering that the South Asia region (SAR) has the second largest poor population in the world, it is essential to improve the frequency and regularity of poverty data. Figure <a href="metadata.html#fig:inv">1.1</a> presents the surveys that make part of the South Asia Micro Database (SARMD). Four countries have released recent rounds of household surveys (Pakistan 2015, Bangladesh 2016, Sri Lanka 2016, and Bhutan 2017) while others are about to release a new round in the next year (Afghanistan 2016, Maldives 2016, India 2017). Nepal has collected five rounds of its Annual Household Survey (AHS) while it waits for the fourth round of the Nepal Living Standards Survey.</p>
<p>Extreme data deprivation may be measured as having less than two data points in a ten year period. The inventory section shows that in 2019 the region of South Asia is not considered extremely data deprived. Still, unless they collect surveys more frequently, three countries are vulnerable to extreme data deprivation by 2022: Bangladesh, Maldives and India.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">knitr::<span class="kw">include_graphics</span>(<span class="st">&quot;figures/Inventory.png&quot;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:inv"></span>
<img src="figures/Inventory.png" alt="SARMD Inventory" width="80%" />
<p class="caption">
Figure 1.1: SARMD Inventory
</p>
</div>
<p>see Figure <a href="metadata.html#fig:inv">1.1</a> at <a href="https://tab.worldbank.org/#/site/WBG/views/SAR_MNA_Metadata/Availability" class="uri">https://tab.worldbank.org/#/site/WBG/views/SAR_MNA_Metadata/Availability</a></p>
</div>
<div id="household-survey-description-by-country" class="section level2">
<h2><span class="header-section-number">1.2</span> Household survey description by country</h2>
<p>The content of these surveys varies widely and their comparison over time even within the same country is a major challenge. We provide a brief overview of survey collection for each country below:</p>
<div id="afghanistan" class="section level3">
<h3><span class="header-section-number">1.2.1</span> Afghanistan</h3>
<p>The Afghanistan Living Conditions Survey (ALCS) 2016-2017 represents the entire population of Afghanistan and may be disaggregated by urban and rural population, and by the nomadic Kuchi population. Previously, the survey was named National Risk and Vulnerability Assessment (NRVA). This survey covers 35 strata, 34 for the provinces of Afghanistan and one for the nomadic Kuchi population. Stratification by season was achieved by equal distribution of data collection over 12 months within the provinces for the latest round between April 2016 and March 2017. In the first three months of fieldwork, areas that were inaccessible due to insecurity were replaced by sampled areas that were scheduled for a later month, in the hope that over time security conditions would improve. Eventually, some clusters in inaccessible areas were replaced by clusters that excluded insecure areas.</p>
<p>The Central Statistics Organization (CSO) (<a href="http://cso.gov.af/" class="uri">http://cso.gov.af/</a>) has used this survey to report that poverty rates in Afghanistan have experienced a sharp increase since 2011-12, especially in rural areas. Households of larger size face a higher poverty rate. Although larger land size is no guarantee for escaping poverty, the smaller the size of land owned by households, the higher is the proportion that falls below the poverty line. Lack of education is another important correlate of poverty in Afghanistan. Low levels of educational attainment are pervasive and households with illiterate heads account for 74 percent of the population.</p>
</div>
<div id="bangladesh" class="section level3">
<h3><span class="header-section-number">1.2.2</span> Bangladesh</h3>
<p>The Household Income and Expenditure Survey (HIES) is the comprehensive nationally representative survey used to measure poverty in Bangladesh. The HIES 2016/17 is the fourth round in the series of HIES conducted by the Bangladesh Bureau of Statistics (BBS) (<a href="http://bbs.gov.bd/" class="uri">http://bbs.gov.bd/</a>) in 2000, 2005, and 2010. As of 2016, Bangladesh had eight administrative divisions. These were Barisal, Chittagong, Dhaka, Khulna, Mymensingh, Rajshahi, Rangpur and Sylhet. These 8 divisions of the country were stratified by rural, urban and city corporation, however, city corporations were only considered for Dhaka, Chittagong, Khulna and Rajshahi. This brought the number of strata to 20 (8 rural divisions, 8 urban divisions, and 4 city corporations).</p>
<p>Based on the HIES 2016, the BBS reports that poverty reduced substantially between 2010 and 2016. In 2010 the poverty headcount ratio, using a higher poverty line, was 31.5% which reduced to 24.3% in 2016. Using a lower poverty line the headcount ratio also reduced from 17.6% in 2010 to 12.9% in 2016. Using the higher upper poverty line, Rangpur had the highest incidence of poverty at 47.2%, followed by Mymensingh 32.8%, Rajshahi 28.9% and Khulna 27.5%. On the other hand, Dhaka recorded the lowest headcount ratio of 16.0%, followed by Sylhet 16.2%, and Chittagong 18.4%.</p>
</div>
<div id="bhutan" class="section level3">
<h3><span class="header-section-number">1.2.3</span> Bhutan</h3>
<p>The Bhutan Living Standards Survey (BLSS) 2017 is the fourth in a series of living standards surveys undertaken by the National Statistics Bureau (NSB) (<a href="http://nsb.gov.bt" class="uri">http://nsb.gov.bt</a>). Earlier surveys were done in 2003, 2007, and 2012 to collect information on the demographics, education, health, employment, housing, access to services, asset ownership, credit, self-perceived poverty, and happiness of the population. The BLSS 2017 included 11,660 households with 48,639 individuals. The sample for BLSS 2017 was designed to provide estimates for a large number of indicators on the living conditions of Bhutanese in both urban and rural areas of the twenty Dzongkhags, including the four Thromdes (Thimphu, Phuentsholing, Gelephu and Samdrup Jongkhar).</p>
<p>The NSB reports a population poverty rate of 8.2% in 2017.The 2017 BLSS shows that the mean monthly household expenditure for the country is Nu33,542: Nu45,508 in urban areas, and Nu26,937 in rural areas. The mean monthly per capita household expenditure is Nu7,939. The monthly per capita household expenditure ofNu11,452 in urban areas is 85% higher than that in rural areas (Nu6,174). The mean per capita expenditure of households in the richest per capita consumption quintile of Nu17,802 is more than seven times that of households in the poorest per capita consumption quintile (Nu2,468).</p>
<p>The NSB has also analyzed subjective happiness ratings by dzongkhags. Pema Gatshel is the happiest Dzongkhag (94%) followed by Samtse (more than 88%) and Trongsa Dzongkhags (more than 86%). The exception is Dagana Dzongkhag, where only four in every 10 respondents reported they are happy.</p>
</div>
<div id="india" class="section level3">
<h3><span class="header-section-number">1.2.4</span> India</h3>
<p>The national poverty estimates for India are based on rounds of Household Consumption Expenditure Surveys conducted by the National Sample Survey Office (NSSO) (<a href="http://mospi.gov.in/" class="uri">http://mospi.gov.in/</a>). The 68th round (July 2011-June 2012) of NSS is designated to measure household consumer expenditure, employment, and unemployment. The 68th round is the most recent round for which consumption data is currently available in SARMD. The survey covers the whole of the Indian Union except interior villages of Nagaland situated beyond five kilometers of the bus route and villages in Andaman and Nicobar Islands which remain inaccessible throughout the year.</p>
<p>In the 68th round two schedule types exist. The two schedule types differ by their reference periods (in the 68th round, Schedule Type 1 and Schedule Type 2 use the same reference periods as in the 66th round). Sample households were divided into two sets: Schedule Type 1 was canvassed in one set and Schedule Type 2 in the other. Schedule Type 1 requires that for certain non-food items (clothing, bedding, footwear, education, medical (institutional), durable goods), the same household should report data for two reference periods: the last 30 days and the last 365 days. For these same non-food items, the reference period used in Schedule Type 2 is only the last 365 days. As in the 66th round, items of food, pan, tobacco and intoxicants (food-plus category) are split into 2 blocks, block 5.1 and block 5.2, instead of being placed in a single block. Block 5.1 consists of cereals, pulses, milk and milk products, sugar and salt. This block has a reference period of 30 days in both Schedule Type 1 and Schedule Type 2. Block 5.2 consists of the other items of food, along with pan, tobacco and intoxicants. This block is assigned a reference period of last 30 days in Schedule Type 1 and a reference period of last 7 days in Schedule Type 2.</p>
</div>
<div id="maldives" class="section level3">
<h3><span class="header-section-number">1.2.5</span> Maldives</h3>
<p>The latest round of the Maldives Household Income and Expenditure Survey (HIES) took place in 2016 with other rounds conducted in 2003 and 2009-10. The sample (4,910 households and 26,453 individuals) was designed by the National Bureau of Statistics (NBS) (<a href="http://statisticsmaldives.gov.mv/" class="uri">http://statisticsmaldives.gov.mv/</a>) in such a way that the results are representative at the individual atoll level and the capital Male’. The HIES 2016 questionnaire was completely revised and includes important survey improvements, particularly in the measurement of poverty, which also hinders comparability with past survey years. Improvements include the inclusion of rent and durable goods in the construction of the welfare aggregate, and change from diary to recall of food items. According to the national poverty line, the poverty is hightest in Gdh. atoll and the lowest is in V. atoll. The Gini coefficient for Maldives is 0.313, and is slightly higher in Male’ than in the Atolls.</p>
</div>
<div id="nepal" class="section level3">
<h3><span class="header-section-number">1.2.6</span> Nepal</h3>
<p>National poverty estimates in Nepal are produced by the Central Bureau of Statistics (CBS) (<a href="http://cbs.gov.np/" class="uri">http://cbs.gov.np/</a>). The last national poverty update in Nepal was based on the 2010 Nepal Living Standard Survey (NLSS-III). The Nepal Living Standards Surveys (NLSS) have been carried out in 1995/96, 2003/04, and 2010/11. These surveys follow the World Bank’s Living Standards Measurement Survey methodology and cover a wide range of topics: demography, consumption, income, access to facilities, housing, education, health, employment, credit, remittances, etc. While the data from the next round of the survey is unlikely to be available until the end of 2019, the CBS has conducted five rounds of the Annual Household Survey (AHS) from 2012-13 to 2016-17. Before the release of the next national poverty rate estimates from NLSS-IV, the World Bank plans to prepare the poverty update report using the recent AHS.</p>
</div>
<div id="pakistan" class="section level3">
<h3><span class="header-section-number">1.2.7</span> Pakistan</h3>
<p>The latest round of the Pakistan Social and Living Standards Measurement Survey (PSLM) 2015-2016 conducted by the Pakistan Bureau of Statistics (PBS) (<a href="http://www.pbs.gov.pk/" class="uri">http://www.pbs.gov.pk/</a>) covers 24,238 households. It provides important information on household income, savings, liabilities, and consumption expenditure and consumption patterns at national and provincial levels. Before this survey, six rounds were conducted during 2004-05, 2005-06, 2007-08, 2010-11, 2011-12 and 2013-14. The survey covers all urban and rural areas of the four provinces of Pakistan (Punjab, Khyber Pakhtunkhwa, Sindh, and Balochistan) excluding Federally Administered Tribal Areas (FATA) and military restricted areas.</p>
</div>
<div id="sri-lanka" class="section level3">
<h3><span class="header-section-number">1.2.8</span> Sri Lanka</h3>
<p>The Household Income and Expenditure Survey (HIES) conducted by the Department of Census and Statistics (DCS) (<a href="http://www.statistics.gov.lk/" class="uri">http://www.statistics.gov.lk/</a>) is the main data source used to calculate poverty indices for Sri Lanka. This survey is conducted once in three years and the latest survey was conducted in January-December 2016. The HIES 2016 is the ninth in the HIES series and covered all 25 districts in the country. The survey provides information on household income and consumption expenditure to measure the changes in living conditions. According to the DCS, the poverty headcount ratio declined from 6.7% in 2012/13 to 4.1% in 2016. Among the districts, Kilinochchi district reported the highest headcount index (18.2%) and Colombo had the lowest (0.9%).</p>
</div>
</div>
<div id="sample-size" class="section level2">
<h2><span class="header-section-number">1.3</span> Sample size</h2>
<p>India’s household survey is by far the largest as shown in Figure <a href="metadata.html#fig:ssize">1.2</a>. The surveys have a stable sample size over time except for Bangladesh 2016, which increased its size compared to its predecessor. All surveys cover both urban and rural areas and the proportion of rural surveys can vary significantly. The latest Afghanistan and Sri Lanka surveys have collected a large proportion of surveys in rural households (above 80% of households).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">knitr::<span class="kw">include_graphics</span>(<span class="st">&quot;figures/Survey_size.png&quot;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:ssize"></span>
<img src="figures/Survey_size.png" alt="Sample Size" width="80%" />
<p class="caption">
Figure 1.2: Sample Size
</p>
</div>
<p>see Figure <a href="metadata.html#fig:ssize">1.2</a> at <a href="https://tab.worldbank.org/#/site/WBG/views/SAR_MNA_Metadata/Lines" class="uri">https://tab.worldbank.org/#/site/WBG/views/SAR_MNA_Metadata/Lines</a></p>
</div>
<div id="expenditure-components" class="section level2">
<h2><span class="header-section-number">1.4</span> Expenditure components</h2>
<p>We consider four main components for a nominal consumption aggregate:</p>
<div id="food" class="section level3">
<h3><span class="header-section-number">1.4.1</span> Food</h3>
<p>The first component is food expenditures, which should include not only food produced and/or consumed at home, but also food purchases outside of home, and food transfers to and from the household. This component is sometimes thought to be easier to measure than non-food. When household members eat from a common pot, it is common to find a single well-informed individual who can act as respondent and provide information about how much the household has consumed. Surveys typically combine a household expenditure diary with the rest of the questionnaire. However, having a food consumption diary is not common in South Asia where most information on food is collected based on weekly recalling what a household has consumed and purchased.</p>
<p>The ideal reference period should be a week, but in this analysis we have found reference periods still vary from monthly to biweekly to daily across surveys. In recent years, the Indian National Sample Survey Organization has experimented with 7-day and 30-day recall periods for a number of items, and discovered that the 7-day recall cuts Indian poverty rates by half, removing some 200 million people from dollar-a-day poverty. This is an issue that has not been much investigated by LSMS surveys, but has recently moved into the forefront of research. In other words, methods matter and it is important to standardize data collection as much as possible. In some cases, food baskets and their collection periods vary even within the same country over time.</p>
<p>In many (but not all) surveys, households report both quantities and expenditures for most of the foods they purchase (e.g. three kilograms of rice for 5 rupees). However, this is not the norm. For example, the Afghanistan Living Conditions Survey 2016 asks what was the amount o each item used in the last seven days, but the price of each item is collected separately through a market price survey.</p>
<p>The food component should include food produced and consumed at home, as well as consumed outside the home, such as at restaurants, cafés, etc. Food transfers are currently measured unevenly with different collection methods and for unsteady baskets of goods. It is more common to find questions regarding tranfers to the household than transfers from the household to other households.</p>
<p>Tabla para comparar: -Number of items -Quantity and/or Value -Diary vs. Recall: -Reference period -Self-production and food away from home -Transfers</p>
<p><a href="https://tab.worldbank.org/#/site/WBG/views/SAR_MNA_Metadata/Food" class="uri">https://tab.worldbank.org/#/site/WBG/views/SAR_MNA_Metadata/Food</a>?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(readr)
food &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;~/SARMD_User_Guidelines/SARMD_guidelines/tables/food.csv&quot;</span>)</code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   Country = col_character(),
##   `Number of food items` = col_double(),
##   `Collection method` = col_character(),
##   `Quantity and/or Value` = col_character(),
##   Transfers = col_logical()
## )</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">knitr::<span class="kw">kable</span>(food,<span class="dt">booktabs=</span><span class="ot">TRUE</span>, <span class="dt">caption =</span> <span class="st">&#39;Food&#39;</span>)</code></pre></div>
<table>
<caption><span id="tab:food">Table 1.2: </span>Food</caption>
<thead>
<tr class="header">
<th align="left">Country</th>
<th align="right">Number of food items</th>
<th align="left">Collection method</th>
<th align="left">Quantity and/or Value</th>
<th align="left">Transfers</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Afghanistan, 2016</td>
<td align="right">92</td>
<td align="left">Recall (weekly)</td>
<td align="left">Quantity</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Bangladesh, 2016</td>
<td align="right">NA</td>
<td align="left">Recall (daily)</td>
<td align="left">Both</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">Bhutan, 2017</td>
<td align="right">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">India, 2017</td>
<td align="right">134</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">Maldives, 2016</td>
<td align="right">146</td>
<td align="left">Recall (weekly)</td>
<td align="left">Both</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Nepal, 2016</td>
<td align="right">97</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">Pakistan, 2015</td>
<td align="right">170</td>
<td align="left">Recal (biweekly)</td>
<td align="left">Both</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Sri Lanka, 2016</td>
<td align="right">198</td>
<td align="left">Recall (weekly)</td>
<td align="left">Both</td>
<td align="left">NA</td>
</tr>
</tbody>
</table>
</div>
<div id="non-food" class="section level3">
<h3><span class="header-section-number">1.4.2</span> Non-food</h3>
<p>The second component, non-food expenditures, includes frequently purchased goods and services like soap, cleaning supplies, newspapers, and personal care items. It also includes some less frequent but regular purchases items like clothing, footwear, kitchen equipment, curtains, bedcovers, etc. Non-food expenditures should at least include alcoholic beverages, tobacco, clothing, water, electricity, fuels, furnishings, health, transport, communication, recreation, and education. A homogenous definition of what constitutes non-food expenditures is required.</p>
<p>Similarly to what found studying the food component, non-food items are also collected for different reference periods, for example, from consumption in the last 30 days, past 3 months, or the last year. Monthly is the most frequent collection period for non-food expenditures.</p>
<p>Both food and non-food expenditures have insufficient coverage on transfers.</p>
<p>Tabla para comparar: Number of items Diary vs. Recall: Quantity and/or Value Reference period Transfers</p>
<p><a href="https://tab.worldbank.org/#/site/WBG/views/SAR_MNA_Metadata/NonFood" class="uri">https://tab.worldbank.org/#/site/WBG/views/SAR_MNA_Metadata/NonFood</a>?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(readr)
nonfood &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;~/SARMD_User_Guidelines/SARMD_guidelines/tables/nonfood.csv&quot;</span>)</code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   Country = col_character(),
##   `Number of non-food items` = col_logical(),
##   `Collection method` = col_logical(),
##   `Quantity and/or Value` = col_logical(),
##   Transfers = col_logical()
## )</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">knitr::<span class="kw">kable</span>(nonfood,<span class="dt">booktabs=</span><span class="ot">TRUE</span>, <span class="dt">caption =</span> <span class="st">&#39;Non-Food&#39;</span>)</code></pre></div>
<table>
<caption><span id="tab:nonfood">Table 1.3: </span>Non-Food</caption>
<thead>
<tr class="header">
<th align="left">Country</th>
<th align="left">Number of non-food items</th>
<th align="left">Collection method</th>
<th align="left">Quantity and/or Value</th>
<th align="left">Transfers</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Afghanistan, 2016</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Bangladesh, 2016</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">Bhutan, 2017</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">India, 2017</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">Maldives, 2016</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Nepal, 2016</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">Pakistan, 2015</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Sri Lanka, 2016</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
</tbody>
</table>
</div>
<div id="durable-assets" class="section level3">
<h3><span class="header-section-number">1.4.3</span> Durable assets</h3>
<p>The third component is consumer flows from durable goods that deliver useful services to a consumer through repeated use over an extended period of time. Long-lived goods (automobiles, appliances, furniture) have a positive and significant impact on living standards. The use of durable goods over time may be measured if surveys at least include quantity, date of purchase, and how much they cost at the time of purchase. Methodologies to measure flows from durable items still differ (e.g. Pakistan 2015 asks only if items were purchased in the last year).</p>
<p>Number of assets Collection method: Quantity and/or Value Comparison between countries</p>
<p><a href="https://tab.worldbank.org/#/site/WBG/views/SAR_MNA_Metadata/Durables" class="uri">https://tab.worldbank.org/#/site/WBG/views/SAR_MNA_Metadata/Durables</a></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(readr)
durables &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;~/SARMD_User_Guidelines/SARMD_guidelines/tables/durables.csv&quot;</span>)</code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   Country = col_character(),
##   `Number of durable items` = col_logical(),
##   `Collection method` = col_logical(),
##   `Quantity and/or Value` = col_logical(),
##   Transfers = col_logical()
## )</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">knitr::<span class="kw">kable</span>(durables,<span class="dt">booktabs=</span><span class="ot">TRUE</span>, <span class="dt">caption =</span> <span class="st">&#39;Durables&#39;</span>)</code></pre></div>
<table>
<caption><span id="tab:durables">Table 1.4: </span>Durables</caption>
<thead>
<tr class="header">
<th align="left">Country</th>
<th align="left">Number of durable items</th>
<th align="left">Collection method</th>
<th align="left">Quantity and/or Value</th>
<th align="left">Transfers</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Afghanistan, 2016</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Bangladesh, 2016</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">Bhutan, 2017</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">India, 2017</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">Maldives, 2016</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Nepal, 2016</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">Pakistan, 2015</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Sri Lanka, 2016</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
</tbody>
</table>
</div>
<div id="housing" class="section level3">
<h3><span class="header-section-number">1.4.4</span> Housing</h3>
<p>The fourth component is rent, which is in some cases observed directly for households who rent their house or apartment. For the rest, rent is obtained either by asking a household how much would you expect to receive each month for this house if you rented it out to someone, or by using a hedonic housing regression model based on dwelling characteristics and actual rent. India and Pakistan still lack sufficient data to measure rents.</p>
<p>Household characteristics: Type of dwelling Area of dwelling Number of bedrooms Number of bathrooms Kitchen Material of the walls, roof, and floor Garage Services (electricity, sanitation, main water source) Rent (actual vs. self-reported vs. imputed)</p>
<p><a href="https://tab.worldbank.org/#/site/WBG/views/SAR_MNA_Metadata/Housing" class="uri">https://tab.worldbank.org/#/site/WBG/views/SAR_MNA_Metadata/Housing</a></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(readr)
housing &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;~/SARMD_User_Guidelines/SARMD_guidelines/tables/housing.csv&quot;</span>)</code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   Country = col_character(),
##   `Number of durable items` = col_logical(),
##   `Collection method` = col_logical(),
##   `Quantity and/or Value` = col_logical(),
##   Transfers = col_logical()
## )</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">knitr::<span class="kw">kable</span>(housing,<span class="dt">booktabs=</span><span class="ot">TRUE</span>, <span class="dt">caption =</span> <span class="st">&#39;Housing&#39;</span>)</code></pre></div>
<table>
<caption><span id="tab:housing">Table 1.5: </span>Housing</caption>
<thead>
<tr class="header">
<th align="left">Country</th>
<th align="left">Number of durable items</th>
<th align="left">Collection method</th>
<th align="left">Quantity and/or Value</th>
<th align="left">Transfers</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Afghanistan, 2016</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Bangladesh, 2016</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">Bhutan, 2017</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">India, 2017</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">Maldives, 2016</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Nepal, 2016</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">Pakistan, 2015</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Sri Lanka, 2016</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introduction-to-south-asia.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="qcheck.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/02-metadata.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
