* Use for example: metaform, filename(consumption surveys metadata.xlsx) directory(/Users/javierparada/Desktop/One Drive/)
/*====================================================================
Project:       Metadata Dashboards
Author:        Javier Parada
Description:   Transforms appended "consumption surveys metadata.xlsx" into
				long format to be used as data source for Tableau dashboards
----------------------------------------------------------------------
Creation Date:    February 1, 2019
====================================================================*/

/*====================================================================
                        0: Program set up
====================================================================*/

capture program drop metaform
program metaform

version 13
syntax [anything] [using] [if] [in], [filename(string) directory(string) ]

qui cd "`directory'"
import excel "`filename'", firstrow clear

*Create new variables:
gen region=Q01_Answer
gen country= Q02_Answer
gen year=Q04_Answer
gen survey_name= Q03_Answer

*Keep most recent record by country and year
gsort country year -date -time
by country year: gen aux=_n
keep if aux==1
drop aux
drop date time

* Dummy for last year of survey
gen last_survey=""
levelsof country, local(clevels)
	foreach c of local clevels {
	qui sum year if country=="`c'"
	replace last_survey="yes" if year==`r(max)' & country=="`c'"
	}
replace last_survey="no" if last_survey==""

*Generate country year variable (group string)
gen country_year=""
tostring year, replace
levelsof year, local(ylevels)
levelsof country, local(clevels)
foreach i of local ylevels {
	foreach j of local clevels {
		replace country_year=`"`j'_`i'"' if country=="`j'" & year=="`i'"
	}
}

display "metaform will transform the survey information contained in `filename' 
display "and save it as a new file named metadata_long.xls in this directory `directory'
list region country_year survey last_survey


/*====================================================================
                        1: Label Variable Questions
====================================================================*/


lab var region "Name of the region"
lab var country "Name of the country"
lab var year "Year of the survey"
lab var survey_name "Name of the survey"

label var Q01_Answer "Region"
label var Q01_Location "Region"
label var Q01_Comments "Region"
label var Q02_Answer "Country"
label var Q02_Location "Country"
label var Q02_Comments "Country"
label var Q03_Answer "Name of the survey"
label var Q03_Location "Name of the survey"
label var Q03_Comments "Name of the survey"
label var Q04_Answer "Year"
label var Q04_Location "Year"
label var Q04_Comments "Year"
label var Q05_Answer "Data collection period"
label var Q05_Location "Data collection period"
label var Q05_Comments "Data collection period"
label var Q06_Answer "Description"
label var Q06_Location "Description"
label var Q06_Comments "Description"
label var Q07_Answer "What is the purpose of the survey?"
label var Q07_Location "What is the purpose of the survey?"
label var Q07_Comments "What is the purpose of the survey?"
label var Q08_Answer "Other purposes"
label var Q08_Location "Other purposes"
label var Q08_Comments "Other purposes"
label var Q09_Answer "Link"
label var Q09_Location "Link"
label var Q09_Comments "Link"

label var S01_Answer "Nationally representative"
label var S01_Location "Nationally representative"
label var S01_Comments "Nationally representative"
label var S02_Answer "Urban (% of households)"
label var S02_Location "Urban (% of households)"
label var S02_Comments "Urban (% of households)"
label var S03_Answer "Rural (% of households)"
label var S03_Location "Rural (% of households)"
label var S03_Comments "Rural (% of households)"
label var S04_Answer "Regional "
label var S04_Location "Regional "
label var S04_Comments "Regional "
label var S05_Answer "Other"
label var S05_Location "Other"
label var S05_Comments "Other"
label var S06_Answer "Number of individuals interviewed "
label var S06_Location "Number of individuals interviewed "
label var S06_Comments "Number of individuals interviewed "
label var S07_Answer "Number of households interviewed "
label var S07_Location "Number of households interviewed "
label var S07_Comments "Number of households interviewed "
label var S08_Answer "Household size"
label var S08_Location "Household size"
label var S08_Comments "Household size"
label var S09_Answer "Sampling method"
label var S09_Location "Sampling method"
label var S09_Comments "Sampling method"
label var S10_Answer "Sampling  with replacement"
label var S10_Location "Sampling  with replacement"
label var S10_Comments "Sampling  with replacement"
label var S11_Answer "Rate of response"
label var S11_Location "Rate of response"
label var S11_Comments "Rate of response"

label var F00_Answer "Total number of food items "
label var F00_Location "Total number of food items "
label var F00_Comments "Total number of food items "
label var F01_Answer "What is the method of data capture?"
label var F01_Location "What is the method of data capture?"
label var F01_Comments "What is the method of data capture?"
label var F02_Answer "What is the reference period for data collection?"
label var F02_Location "What is the reference period for data collection?"
label var F02_Comments "What is the reference period for data collection?"
label var F03_Answer "Does the survey collect information on consumption or expenditures?"
label var F03_Location "Does the survey collect information on consumption or expenditures?"
label var F03_Comments "Does the survey collect information on consumption or expenditures?"
label var F04_Answer "Does the survey collect data on quantities?"
label var F04_Location "Does the survey collect data on quantities?"
label var F04_Comments "Does the survey collect data on quantities?"
label var F05_Answer "Does the survey collect data on values?"
label var F05_Location "Does the survey collect data on values?"
label var F05_Comments "Does the survey collect data on values?"
label var F06_Answer "What is the method of data capture?"
label var F06_Location "What is the method of data capture?"
label var F06_Comments "What is the method of data capture?"
label var F07_Answer "What is the reference period for data collection?"
label var F07_Location "What is the reference period for data collection?"
label var F07_Comments "What is the reference period for data collection?"
label var F08_Answer "Does the survey collect information on consumption or expenditures?"
label var F08_Location "Does the survey collect information on consumption or expenditures?"
label var F08_Comments "Does the survey collect information on consumption or expenditures?"
label var F09_Answer "Does the survey collect data on quantities?"
label var F09_Location "Does the survey collect data on quantities?"
label var F09_Comments "Does the survey collect data on quantities?"
label var F10_Answer "Does the survey collect data on values?"
label var F10_Location "Does the survey collect data on values?"
label var F10_Comments "Does the survey collect data on values?"
label var F11_Answer "What is the method of data capture?"
label var F11_Location "What is the method of data capture?"
label var F11_Comments "What is the method of data capture?"
label var F12_Answer "What is the reference period for data collection?"
label var F12_Location "What is the reference period for data collection?"
label var F12_Comments "What is the reference period for data collection?"
label var F13_Answer "Does the survey collect information on consumption or expenditures?"
label var F13_Location "Does the survey collect information on consumption or expenditures?"
label var F13_Comments "Does the survey collect information on consumption or expenditures?"
label var F14_Answer "Does the survey collect data on quantities?"
label var F14_Location "Does the survey collect data on quantities?"
label var F14_Comments "Does the survey collect data on quantities?"
label var F15_Answer "Does the survey collect data on values?"
label var F15_Location "Does the survey collect data on values?"
label var F15_Comments "Does the survey collect data on values?"
label var F16_Answer "What is the method of data capture?"
label var F16_Location "What is the method of data capture?"
label var F16_Comments "What is the method of data capture?"
label var F17_Answer "What is the reference period for data collection?"
label var F17_Location "What is the reference period for data collection?"
label var F17_Comments "What is the reference period for data collection?"
label var F18_Answer "Does the survey collect information on consumption or expenditures?"
label var F18_Location "Does the survey collect information on consumption or expenditures?"
label var F18_Comments "Does the survey collect information on consumption or expenditures?"
label var F19_Answer "Does the survey collect data on quantities?"
label var F19_Location "Does the survey collect data on quantities?"
label var F19_Comments "Does the survey collect data on quantities?"
label var F20_Answer "Does the survey collect data on values?"
label var F20_Location "Does the survey collect data on values?"
label var F20_Comments "Does the survey collect data on values?"
label var F21_Answer "What is the method of data capture?"
label var F21_Location "What is the method of data capture?"
label var F21_Comments "What is the method of data capture?"
label var F22_Answer "What is the reference period for data collection?"
label var F22_Location "What is the reference period for data collection?"
label var F22_Comments "What is the reference period for data collection?"
label var F23_Answer "Does the survey collect information on consumption or expenditures?"
label var F23_Location "Does the survey collect information on consumption or expenditures?"
label var F23_Comments "Does the survey collect information on consumption or expenditures?"
label var F24_Answer "Does the survey collect data on quantities?"
label var F24_Location "Does the survey collect data on quantities?"
label var F24_Comments "Does the survey collect data on quantities?"
label var F25_Answer "Does the survey collect data on values?"
label var F25_Location "Does the survey collect data on values?"
label var F25_Comments "Does the survey collect data on values?"

label var N00_Answer "Total number of non-food items "
label var N00_Location "Total number of non-food items "
label var N00_Comments "Total number of non-food items "
label var N01_Answer "What is the reference period for data collection?"
label var N01_Location "What is the reference period for data collection?"
label var N01_Comments "What is the reference period for data collection?"
label var N02_Answer "Does the survey collect data on quantities?"
label var N02_Location "Does the survey collect data on quantities?"
label var N02_Comments "Does the survey collect data on quantities?"
label var N03_Answer "Does the survey collect data on values?"
label var N03_Location "Does the survey collect data on values?"
label var N03_Comments "Does the survey collect data on values?"
label var N04_Answer "Is there information on in-kind transfers to/from the household?"
label var N04_Location "Is there information on in-kind transfers to/from the household?"
label var N04_Comments "Is there information on in-kind transfers to/from the household?"
label var N05_Answer "What is the reference period for data collection?"
label var N05_Location "What is the reference period for data collection?"
label var N05_Comments "What is the reference period for data collection?"
label var N06_Answer "Does the survey collect data on quantities?"
label var N06_Location "Does the survey collect data on quantities?"
label var N06_Comments "Does the survey collect data on quantities?"
label var N07_Answer "Does the survey collect data on values?"
label var N07_Location "Does the survey collect data on values?"
label var N07_Comments "Does the survey collect data on values?"
label var N08_Answer "Is there information on in-kind transfers to/from the household?"
label var N08_Location "Is there information on in-kind transfers to/from the household?"
label var N08_Comments "Is there information on in-kind transfers to/from the household?"
label var N09_Answer "What is the reference period for data collection?"
label var N09_Location "What is the reference period for data collection?"
label var N09_Comments "What is the reference period for data collection?"
label var N10_Answer "Does the survey collect data on quantities?"
label var N10_Location "Does the survey collect data on quantities?"
label var N10_Comments "Does the survey collect data on quantities?"
label var N11_Answer "Does the survey collect data on values?"
label var N11_Location "Does the survey collect data on values?"
label var N11_Comments "Does the survey collect data on values?"
label var N12_Answer "Is there information on in-kind transfers to/from the household?"
label var N12_Location "Is there information on in-kind transfers to/from the household?"
label var N12_Comments "Is there information on in-kind transfers to/from the household?"
label var N13_Answer "What is the reference period for data collection?"
label var N13_Location "What is the reference period for data collection?"
label var N13_Comments "What is the reference period for data collection?"
label var N14_Answer "Does the survey collect data on quantities?"
label var N14_Location "Does the survey collect data on quantities?"
label var N14_Comments "Does the survey collect data on quantities?"
label var N15_Answer "Does the survey collect data on values?"
label var N15_Location "Does the survey collect data on values?"
label var N15_Comments "Does the survey collect data on values?"
label var N16_Answer "Is there information on in-kind transfers to/from the household?"
label var N16_Location "Is there information on in-kind transfers to/from the household?"
label var N16_Comments "Is there information on in-kind transfers to/from the household?"
label var N17_Answer "What is the reference period for data collection?"
label var N17_Location "What is the reference period for data collection?"
label var N17_Comments "What is the reference period for data collection?"
label var N18_Answer "Does the survey collect data on quantities?"
label var N18_Location "Does the survey collect data on quantities?"
label var N18_Comments "Does the survey collect data on quantities?"
label var N19_Answer "Does the survey collect data on values?"
label var N19_Location "Does the survey collect data on values?"
label var N19_Comments "Does the survey collect data on values?"
label var N20_Answer "Is there information on in-kind transfers to/from the household?"
label var N20_Location "Is there information on in-kind transfers to/from the household?"
label var N20_Comments "Is there information on in-kind transfers to/from the household?"
label var N21_Answer "What is the reference period for data collection?"
label var N21_Location "What is the reference period for data collection?"
label var N21_Comments "What is the reference period for data collection?"
label var N22_Answer "Does the survey collect data on quantities?"
label var N22_Location "Does the survey collect data on quantities?"
label var N22_Comments "Does the survey collect data on quantities?"
label var N23_Answer "Does the survey collect data on values?"
label var N23_Location "Does the survey collect data on values?"
label var N23_Comments "Does the survey collect data on values?"
label var N24_Answer "Is there information on in-kind transfers to/from the household?"
label var N24_Location "Is there information on in-kind transfers to/from the household?"
label var N24_Comments "Is there information on in-kind transfers to/from the household?"
label var N25_Answer "What is the reference period for data collection?"
label var N25_Location "What is the reference period for data collection?"
label var N25_Comments "What is the reference period for data collection?"
label var N26_Answer "Does the survey collect data on quantities?"
label var N26_Location "Does the survey collect data on quantities?"
label var N26_Comments "Does the survey collect data on quantities?"
label var N27_Answer "Does the survey collect data on values?"
label var N27_Location "Does the survey collect data on values?"
label var N27_Comments "Does the survey collect data on values?"
label var N28_Answer "Is there information on in-kind transfers to/from the household?"
label var N28_Location "Is there information on in-kind transfers to/from the household?"
label var N28_Comments "Is there information on in-kind transfers to/from the household?"
label var N29_Answer "What is the reference period for data collection?"
label var N29_Location "What is the reference period for data collection?"
label var N29_Comments "What is the reference period for data collection?"
label var N30_Answer "Does the survey collect data on quantities?"
label var N30_Location "Does the survey collect data on quantities?"
label var N30_Comments "Does the survey collect data on quantities?"
label var N31_Answer "Does the survey collect data on values?"
label var N31_Location "Does the survey collect data on values?"
label var N31_Comments "Does the survey collect data on values?"
label var N32_Answer "Is there information on in-kind transfers to/from the household?"
label var N32_Location "Is there information on in-kind transfers to/from the household?"
label var N32_Comments "Is there information on in-kind transfers to/from the household?"
label var N33_Answer "What is the reference period for data collection?"
label var N33_Location "What is the reference period for data collection?"
label var N33_Comments "What is the reference period for data collection?"
label var N34_Answer "Does the survey collect data on quantities?"
label var N34_Location "Does the survey collect data on quantities?"
label var N34_Comments "Does the survey collect data on quantities?"
label var N35_Answer "Does the survey collect data on values?"
label var N35_Location "Does the survey collect data on values?"
label var N35_Comments "Does the survey collect data on values?"
label var N36_Answer "Is there information on in-kind transfers to/from the household?"
label var N36_Location "Is there information on in-kind transfers to/from the household?"
label var N36_Comments "Is there information on in-kind transfers to/from the household?"
label var N37_Answer "What is the reference period for data collection?"
label var N37_Location "What is the reference period for data collection?"
label var N37_Comments "What is the reference period for data collection?"
label var N38_Answer "Does the survey collect data on quantities?"
label var N38_Location "Does the survey collect data on quantities?"
label var N38_Comments "Does the survey collect data on quantities?"
label var N39_Answer "Does the survey collect data on values?"
label var N39_Location "Does the survey collect data on values?"
label var N39_Comments "Does the survey collect data on values?"
label var N40_Answer "Is there information on in-kind transfers to/from the household?"
label var N40_Location "Is there information on in-kind transfers to/from the household?"
label var N40_Comments "Is there information on in-kind transfers to/from the household?"
label var N41_Answer "What is the reference period for data collection?"
label var N41_Location "What is the reference period for data collection?"
label var N41_Comments "What is the reference period for data collection?"
label var N42_Answer "Does the survey collect data on quantities?"
label var N42_Location "Does the survey collect data on quantities?"
label var N42_Comments "Does the survey collect data on quantities?"
label var N43_Answer "Does the survey collect data on values?"
label var N43_Location "Does the survey collect data on values?"
label var N43_Comments "Does the survey collect data on values?"
label var N44_Answer "Is there information on in-kind transfers to/from the household?"
label var N44_Location "Is there information on in-kind transfers to/from the household?"
label var N44_Comments "Is there information on in-kind transfers to/from the household?"

label var D01_Answer "Total number of durable items "
label var D01_Location "Total number of durable items "
label var D01_Comments "Total number of durable items "
label var D02_Answer "Does the survey collect data on quantities for durables?"
label var D02_Location "Does the survey collect data on quantities for durables?"
label var D02_Comments "Does the survey collect data on quantities for durables?"
label var D03_Answer "Does the survey collect data on values for durables?"
label var D03_Location "Does the survey collect data on values for durables?"
label var D03_Comments "Does the survey collect data on values for durables?"
label var D04_Answer "What is the number of a certain type that the survey collects information for?"
label var D04_Location "What is the number of a certain type that the survey collects information for?"
label var D04_Comments "What is the number of a certain type that the survey collects information for?"
label var D05_Answer "Is there information about the year of purchase/acquisition of durable goods?"
label var D05_Location "Is there information about the year of purchase/acquisition of durable goods?"
label var D05_Comments "Is there information about the year of purchase/acquisition of durable goods?"
label var D06_Answer "Is there information about the value of durable goods at purchase?"
label var D06_Location "Is there information about the value of durable goods at purchase?"
label var D06_Comments "Is there information about the value of durable goods at purchase?"
label var D07_Answer "Is there information about the current value of the good?"
label var D07_Location "Is there information about the current value of the good?"
label var D07_Comments "Is there information about the current value of the good?"
label var D08_Answer "Is there information on in-kind transfers of durable goods to the household?"
label var D08_Location "Is there information on in-kind transfers of durable goods to the household?"
label var D08_Comments "Is there information on in-kind transfers of durable goods to the household?"

label var H01_Answer "Type of dwellling (house, apartment, etc.)"
label var H01_Location "Type of dwellling (house, apartment, etc.)"
label var H01_Comments "Type of dwellling (house, apartment, etc.)"
label var H02_Answer "Area of the dwelling"
label var H02_Location "Area of the dwelling"
label var H02_Comments "Area of the dwelling"
label var H03_Answer "Number of bedrooms"
label var H03_Location "Number of bedrooms"
label var H03_Comments "Number of bedrooms"
label var H04_Answer "Kitchen"
label var H04_Location "Kitchen"
label var H04_Comments "Kitchen"
label var H05_Answer "Number of bathrooms"
label var H05_Location "Number of bathrooms"
label var H05_Comments "Number of bathrooms"
label var H06_Answer "Material of the walls"
label var H06_Location "Material of the walls"
label var H06_Comments "Material of the walls"
label var H07_Answer "Material of the roof"
label var H07_Location "Material of the roof"
label var H07_Comments "Material of the roof"
label var H08_Answer "Material of the floor"
label var H08_Location "Material of the floor"
label var H08_Comments "Material of the floor"
label var H09_Answer "Garage"
label var H09_Location "Garage"
label var H09_Comments "Garage"
label var H10_Answer "Access to public transportation"
label var H10_Location "Access to public transportation"
label var H10_Comments "Access to public transportation"
label var H11_Answer "Others (specify in comments)"
label var H11_Location "Others (specify in comments)"
label var H11_Comments "Others (specify in comments)"
label var H12_Answer "Electricity (list categories in comments)"
label var H12_Location "Electricity (list categories in comments)"
label var H12_Comments "Electricity (list categories in comments)"
label var H13_Answer "Sanitation (list categories in comments)"
label var H13_Location "Sanitation (list categories in comments)"
label var H13_Comments "Sanitation (list categories in comments)"
label var H14_Answer "Water (list categories in comments)"
label var H14_Location "Water (list categories in comments)"
label var H14_Comments "Water (list categories in comments)"
label var H15_Answer "Other services, e.g. internet, garbage collection, etc. (list in comments)"
label var H15_Location "Other services, e.g. internet, garbage collection, etc. (list in comments)"
label var H15_Comments "Other services, e.g. internet, garbage collection, etc. (list in comments)"
label var H16_Answer "Is there information on the amount of rent paid?"
label var H16_Location "Is there information on the amount of rent paid?"
label var H16_Comments "Is there information on the amount of rent paid?"
label var H17_Answer "What is the reference period for data collection?"
label var H17_Location "What is the reference period for data collection?"
label var H17_Comments "What is the reference period for data collection?"
label var H18_Answer "Does the amount of rent paid includes utilities?"
label var H18_Location "Does the amount of rent paid includes utilities?"
label var H18_Comments "Does the amount of rent paid includes utilities?"
label var H19_Answer "Is there information about subsidized housing?"
label var H19_Location "Is there information about subsidized housing?"
label var H19_Comments "Is there information about subsidized housing?"
label var H20_Answer "What is the reference period for data collection?"
label var H20_Location "What is the reference period for data collection?"
label var H20_Comments "What is the reference period for data collection?"
label var H21_Answer "Is there information on self-reported rent (write down the question in comments)?"
label var H21_Location "Is there information on self-reported rent (write down the question in comments)?"
label var H21_Comments "Is there information on self-reported rent (write down the question in comments)?"
label var H22_Answer "What is the reference period for data collection?"
label var H22_Location "What is the reference period for data collection?"
label var H22_Comments "What is the reference period for data collection?"
label var H23_Answer "Is there information mortgage payments?"
label var H23_Location "Is there information mortgage payments?"
label var H23_Comments "Is there information mortgage payments?"
label var H24_Answer "What is the reference period for data collection?"
label var H24_Location "What is the reference period for data collection?"
label var H24_Comments "What is the reference period for data collection?"
label var H25_Answer "Is there information on imputed rents?  (If yes, describe in comments the method used)"
label var H25_Location "Is there information on imputed rents?  (If yes, describe in comments the method used)"
label var H25_Comments "Is there information on imputed rents?  (If yes, describe in comments the method used)"

label var C01_Answer "1.1 Food"
label var C01_Location "1.1 Food"
label var C01_Comments "1.1 Food"
label var C02_Answer "1.2 Non-alcoholic beverages"
label var C02_Location "1.2 Non-alcoholic beverages"
label var C02_Comments "1.2 Non-alcoholic beverages"
label var C03_Answer "2.1 Alcoholic beverages"
label var C03_Location "2.1 Alcoholic beverages"
label var C03_Comments "2.1 Alcoholic beverages"
label var C04_Answer "2.2 Tobacco"
label var C04_Location "2.2 Tobacco"
label var C04_Comments "2.2 Tobacco"
label var C05_Answer "2.3 Narcotics"
label var C05_Location "2.3 Narcotics"
label var C05_Comments "2.3 Narcotics"
label var C06_Answer "3.1 Clothing"
label var C06_Location "3.1 Clothing"
label var C06_Comments "3.1 Clothing"
label var C07_Answer "3.2 Footwear"
label var C07_Location "3.2 Footwear"
label var C07_Comments "3.2 Footwear"
label var C08_Answer "4.1 Actual rentals for housing"
label var C08_Location "4.1 Actual rentals for housing"
label var C08_Comments "4.1 Actual rentals for housing"
label var C09_Answer "4.2 Imputed rentals for housing"
label var C09_Location "4.2 Imputed rentals for housing"
label var C09_Comments "4.2 Imputed rentals for housing"
label var C10_Answer "4.3 Maintenance and repair of the dwelling"
label var C10_Location "4.3 Maintenance and repair of the dwelling"
label var C10_Comments "4.3 Maintenance and repair of the dwelling"
label var C11_Answer "4.4 Water supply and miscellaneous services relating to the dwelling"
label var C11_Location "4.4 Water supply and miscellaneous services relating to the dwelling"
label var C11_Comments "4.4 Water supply and miscellaneous services relating to the dwelling"
label var C12_Answer "4.5 Electricity, gas and other fuels"
label var C12_Location "4.5 Electricity, gas and other fuels"
label var C12_Comments "4.5 Electricity, gas and other fuels"
label var C13_Answer "5.1 Furniture and furnishings, carpets and other floor coverings"
label var C13_Location "5.1 Furniture and furnishings, carpets and other floor coverings"
label var C13_Comments "5.1 Furniture and furnishings, carpets and other floor coverings"
label var C14_Answer "5.2 Household textiles"
label var C14_Location "5.2 Household textiles"
label var C14_Comments "5.2 Household textiles"
label var C15_Answer "5.3 Household appliances"
label var C15_Location "5.3 Household appliances"
label var C15_Comments "5.3 Household appliances"
label var C16_Answer "5.4 Glassware, tableware and household utensils"
label var C16_Location "5.4 Glassware, tableware and household utensils"
label var C16_Comments "5.4 Glassware, tableware and household utensils"
label var C17_Answer "5.5 Tools and equipment for house and garden"
label var C17_Location "5.5 Tools and equipment for house and garden"
label var C17_Comments "5.5 Tools and equipment for house and garden"
label var C18_Answer "5.6 Goods and services for routine household maintenance"
label var C18_Location "5.6 Goods and services for routine household maintenance"
label var C18_Comments "5.6 Goods and services for routine household maintenance"
label var C19_Answer "6.1 Medical products, appliances and equipment"
label var C19_Location "6.1 Medical products, appliances and equipment"
label var C19_Comments "6.1 Medical products, appliances and equipment"
label var C20_Answer "6.2 Outpatient services"
label var C20_Location "6.2 Outpatient services"
label var C20_Comments "6.2 Outpatient services"
label var C21_Answer "6.3 Hospital services"
label var C21_Location "6.3 Hospital services"
label var C21_Comments "6.3 Hospital services"
label var C22_Answer "7.1 Purchase of vehicles"
label var C22_Location "7.1 Purchase of vehicles"
label var C22_Comments "7.1 Purchase of vehicles"
label var C23_Answer "7.2 Operation of personal transport equipment"
label var C23_Location "7.2 Operation of personal transport equipment"
label var C23_Comments "7.2 Operation of personal transport equipment"
label var C24_Answer "7.3 Transport services"
label var C24_Location "7.3 Transport services"
label var C24_Comments "7.3 Transport services"
label var C25_Answer "8.1 Postal services"
label var C25_Location "8.1 Postal services"
label var C25_Comments "8.1 Postal services"
label var C26_Answer "8.2 Telephone and telefax equipment"
label var C26_Location "8.2 Telephone and telefax equipment"
label var C26_Comments "8.2 Telephone and telefax equipment"
label var C27_Answer "8.3 Telephone and telefax services"
label var C27_Location "8.3 Telephone and telefax services"
label var C27_Comments "8.3 Telephone and telefax services"
label var C28_Answer "9.1 Audio-visual, photographic and information processing equipment"
label var C28_Location "9.1 Audio-visual, photographic and information processing equipment"
label var C28_Comments "9.1 Audio-visual, photographic and information processing equipment"
label var C29_Answer "9.2 Other major durables for recreation and culture"
label var C29_Location "9.2 Other major durables for recreation and culture"
label var C29_Comments "9.2 Other major durables for recreation and culture"
label var C30_Answer "9.3 Other recreational items and equipment, gardens and pets"
label var C30_Location "9.3 Other recreational items and equipment, gardens and pets"
label var C30_Comments "9.3 Other recreational items and equipment, gardens and pets"
label var C31_Answer "9.4 Recreational and cultural services"
label var C31_Location "9.4 Recreational and cultural services"
label var C31_Comments "9.4 Recreational and cultural services"
label var C32_Answer "9.5 Newspapers, books and stationery"
label var C32_Location "9.5 Newspapers, books and stationery"
label var C32_Comments "9.5 Newspapers, books and stationery"
label var C33_Answer "9.6 Package holidays"
label var C33_Location "9.6 Package holidays"
label var C33_Comments "9.6 Package holidays"
label var C34_Answer "10.1 Pre-primary and primary education"
label var C34_Location "10.1 Pre-primary and primary education"
label var C34_Comments "10.1 Pre-primary and primary education"
label var C35_Answer "10.2 Secondary education"
label var C35_Location "10.2 Secondary education"
label var C35_Comments "10.2 Secondary education"
label var C36_Answer "10.3 Post-secondary non-tertiary education"
label var C36_Location "10.3 Post-secondary non-tertiary education"
label var C36_Comments "10.3 Post-secondary non-tertiary education"
label var C37_Answer "10.4 Tertiary education"
label var C37_Location "10.4 Tertiary education"
label var C37_Comments "10.4 Tertiary education"
label var C38_Answer "10.5 Education not definable by level"
label var C38_Location "10.5 Education not definable by level"
label var C38_Comments "10.5 Education not definable by level"
label var C39_Answer "11.1 Catering services"
label var C39_Location "11.1 Catering services"
label var C39_Comments "11.1 Catering services"
label var C40_Answer "11.2 Accommodation services"
label var C40_Location "11.2 Accommodation services"
label var C40_Comments "11.2 Accommodation services"
label var C41_Answer "12.1 Personal care"
label var C41_Location "12.1 Personal care"
label var C41_Comments "12.1 Personal care"
label var C42_Answer "12.2 Prostitution"
label var C42_Location "12.2 Prostitution"
label var C42_Comments "12.2 Prostitution"
label var C43_Answer "12.3 Personal effects n.e.c."
label var C43_Location "12.3 Personal effects n.e.c."
label var C43_Comments "12.3 Personal effects n.e.c."
label var C44_Answer "12.4 Social protection"
label var C44_Location "12.4 Social protection"
label var C44_Comments "12.4 Social protection"
label var C45_Answer "12.5 Insurance"
label var C45_Location "12.5 Insurance"
label var C45_Comments "12.5 Insurance"
label var C46_Answer "12.6 Financial services n.e.c."
label var C46_Location "12.6 Financial services n.e.c."
label var C46_Comments "12.6 Financial services n.e.c."
label var C47_Answer "12.7 Other services n.e.c."
label var C47_Location "12.7 Other services n.e.c."
label var C47_Comments "12.7 Other services n.e.c."



* Check for missings
cap ssc install missings
missings report 
local variables `r(varlist)'

foreach var of local variables {
di ""
di ""
di "Variable `var' : `: var la `var''" 
di "Missing values by country:" 
tab country year if `var'==""
}

/*====================================================================
             2: Create inventory of existing surveys
====================================================================*/
preserve
gen inventory="Yes"
keep country year inventory
reshape wide inventory, i(country) j(year) string
rename inventory* y*
forvalues i=1997/2015 {
	capture replace y`i'="No" if y`i'==""
}

*export excel using "${root_out}\\inventory.xlsx", firstrow(var) replace
restore


/*====================================================================
         3: Tag Surveys that can't be harmonized
====================================================================*/

*drop FP  purpose other_purposes
*rename Q* ResponseQ*

*gen harmonize="No"
*replace harmonize="Yes" if (ResponseQ_31=="Yes" | ResponseQ_32=="Yes") & (country!="Argentina" & country!="Haiti" & country!="Jamaica" & country!="Mexico")

/*====================================================================
         4: Clean and reshape into Tableau compatible data
====================================================================*/

tostring Q* S* F* N* D* H* C*, replace force
rename * Row_*
rename Row_region region
rename Row_country country
rename Row_year year
rename Row_country_year country_year
rename Row_survey_name survey_name
rename Row_user user
rename Row_last_survey last_survey

reshape long Row_, i(region country year country_year survey_name user last_survey) string

rename _j Q
rename Row_ Response

/*====================================================================
Generate descriptions
====================================================================*/
gen description=""
replace description="Region" if Q=="Q01_Answer"
replace description="Region" if Q=="Q01_Location"
replace description="Region" if Q=="Q01_Comments"
replace description="Country" if Q=="Q02_Answer"
replace description="Country" if Q=="Q02_Location"
replace description="Country" if Q=="Q02_Comments"
replace description="Name of the survey" if Q=="Q03_Answer"
replace description="Name of the survey" if Q=="Q03_Location"
replace description="Name of the survey" if Q=="Q03_Comments"
replace description="Year" if Q=="Q04_Answer"
replace description="Year" if Q=="Q04_Location"
replace description="Year" if Q=="Q04_Comments"
replace description="Data collection period" if Q=="Q05_Answer"
replace description="Data collection period" if Q=="Q05_Location"
replace description="Data collection period" if Q=="Q05_Comments"
replace description="Description" if Q=="Q06_Answer"
replace description="Description" if Q=="Q06_Location"
replace description="Description" if Q=="Q06_Comments"
replace description="What is the purpose of the survey?" if Q=="Q07_Answer"
replace description="What is the purpose of the survey?" if Q=="Q07_Location"
replace description="What is the purpose of the survey?" if Q=="Q07_Comments"
replace description="Other purposes" if Q=="Q08_Answer"
replace description="Other purposes" if Q=="Q08_Location"
replace description="Other purposes" if Q=="Q08_Comments"
replace description="Link" if Q=="Q09_Answer"
replace description="Link" if Q=="Q09_Location"
replace description="Link" if Q=="Q09_Comments"
replace description="Nationally representative" if Q=="S01_Answer"
replace description="Nationally representative" if Q=="S01_Location"
replace description="Nationally representative" if Q=="S01_Comments"
replace description="Urban (% of households)" if Q=="S02_Answer"
replace description="Urban (% of households)" if Q=="S02_Location"
replace description="Urban (% of households)" if Q=="S02_Comments"
replace description="Rural (% of households)" if Q=="S03_Answer"
replace description="Rural (% of households)" if Q=="S03_Location"
replace description="Rural (% of households)" if Q=="S03_Comments"
replace description="Regional " if Q=="S04_Answer"
replace description="Regional " if Q=="S04_Location"
replace description="Regional " if Q=="S04_Comments"
replace description="Other" if Q=="S05_Answer"
replace description="Other" if Q=="S05_Location"
replace description="Other" if Q=="S05_Comments"
replace description="Number of individuals interviewed " if Q=="S06_Answer"
replace description="Number of individuals interviewed " if Q=="S06_Location"
replace description="Number of individuals interviewed " if Q=="S06_Comments"
replace description="Number of households interviewed " if Q=="S07_Answer"
replace description="Number of households interviewed " if Q=="S07_Location"
replace description="Number of households interviewed " if Q=="S07_Comments"
replace description="Household size" if Q=="S08_Answer"
replace description="Household size" if Q=="S08_Location"
replace description="Household size" if Q=="S08_Comments"
replace description="Sampling method" if Q=="S09_Answer"
replace description="Sampling method" if Q=="S09_Location"
replace description="Sampling method" if Q=="S09_Comments"
replace description="Sampling  with replacement" if Q=="S10_Answer"
replace description="Sampling  with replacement" if Q=="S10_Location"
replace description="Sampling  with replacement" if Q=="S10_Comments"
replace description="Rate of response" if Q=="S11_Answer"
replace description="Rate of response" if Q=="S11_Location"
replace description="Rate of response" if Q=="S11_Comments"
replace description="Total number of food items " if Q=="F00_Answer"
replace description="Total number of food items " if Q=="F00_Location"
replace description="Total number of food items " if Q=="F00_Comments"
replace description="What is the method of data capture?" if Q=="F01_Answer"
replace description="What is the method of data capture?" if Q=="F01_Location"
replace description="What is the method of data capture?" if Q=="F01_Comments"
replace description="What is the reference period for data collection?" if Q=="F02_Answer"
replace description="What is the reference period for data collection?" if Q=="F02_Location"
replace description="What is the reference period for data collection?" if Q=="F02_Comments"
replace description="Does the survey collect information on consumption or expenditures?" if Q=="F03_Answer"
replace description="Does the survey collect information on consumption or expenditures?" if Q=="F03_Location"
replace description="Does the survey collect information on consumption or expenditures?" if Q=="F03_Comments"
replace description="Does the survey collect data on quantities?" if Q=="F04_Answer"
replace description="Does the survey collect data on quantities?" if Q=="F04_Location"
replace description="Does the survey collect data on quantities?" if Q=="F04_Comments"
replace description="Does the survey collect data on values?" if Q=="F05_Answer"
replace description="Does the survey collect data on values?" if Q=="F05_Location"
replace description="Does the survey collect data on values?" if Q=="F05_Comments"
replace description="What is the method of data capture?" if Q=="F06_Answer"
replace description="What is the method of data capture?" if Q=="F06_Location"
replace description="What is the method of data capture?" if Q=="F06_Comments"
replace description="What is the reference period for data collection?" if Q=="F07_Answer"
replace description="What is the reference period for data collection?" if Q=="F07_Location"
replace description="What is the reference period for data collection?" if Q=="F07_Comments"
replace description="Does the survey collect information on consumption or expenditures?" if Q=="F08_Answer"
replace description="Does the survey collect information on consumption or expenditures?" if Q=="F08_Location"
replace description="Does the survey collect information on consumption or expenditures?" if Q=="F08_Comments"
replace description="Does the survey collect data on quantities?" if Q=="F09_Answer"
replace description="Does the survey collect data on quantities?" if Q=="F09_Location"
replace description="Does the survey collect data on quantities?" if Q=="F09_Comments"
replace description="Does the survey collect data on values?" if Q=="F10_Answer"
replace description="Does the survey collect data on values?" if Q=="F10_Location"
replace description="Does the survey collect data on values?" if Q=="F10_Comments"
replace description="What is the method of data capture?" if Q=="F11_Answer"
replace description="What is the method of data capture?" if Q=="F11_Location"
replace description="What is the method of data capture?" if Q=="F11_Comments"
replace description="What is the reference period for data collection?" if Q=="F12_Answer"
replace description="What is the reference period for data collection?" if Q=="F12_Location"
replace description="What is the reference period for data collection?" if Q=="F12_Comments"
replace description="Does the survey collect information on consumption or expenditures?" if Q=="F13_Answer"
replace description="Does the survey collect information on consumption or expenditures?" if Q=="F13_Location"
replace description="Does the survey collect information on consumption or expenditures?" if Q=="F13_Comments"
replace description="Does the survey collect data on quantities?" if Q=="F14_Answer"
replace description="Does the survey collect data on quantities?" if Q=="F14_Location"
replace description="Does the survey collect data on quantities?" if Q=="F14_Comments"
replace description="Does the survey collect data on values?" if Q=="F15_Answer"
replace description="Does the survey collect data on values?" if Q=="F15_Location"
replace description="Does the survey collect data on values?" if Q=="F15_Comments"
replace description="What is the method of data capture?" if Q=="F16_Answer"
replace description="What is the method of data capture?" if Q=="F16_Location"
replace description="What is the method of data capture?" if Q=="F16_Comments"
replace description="What is the reference period for data collection?" if Q=="F17_Answer"
replace description="What is the reference period for data collection?" if Q=="F17_Location"
replace description="What is the reference period for data collection?" if Q=="F17_Comments"
replace description="Does the survey collect information on consumption or expenditures?" if Q=="F18_Answer"
replace description="Does the survey collect information on consumption or expenditures?" if Q=="F18_Location"
replace description="Does the survey collect information on consumption or expenditures?" if Q=="F18_Comments"
replace description="Does the survey collect data on quantities?" if Q=="F19_Answer"
replace description="Does the survey collect data on quantities?" if Q=="F19_Location"
replace description="Does the survey collect data on quantities?" if Q=="F19_Comments"
replace description="Does the survey collect data on values?" if Q=="F20_Answer"
replace description="Does the survey collect data on values?" if Q=="F20_Location"
replace description="Does the survey collect data on values?" if Q=="F20_Comments"
replace description="What is the method of data capture?" if Q=="F21_Answer"
replace description="What is the method of data capture?" if Q=="F21_Location"
replace description="What is the method of data capture?" if Q=="F21_Comments"
replace description="What is the reference period for data collection?" if Q=="F22_Answer"
replace description="What is the reference period for data collection?" if Q=="F22_Location"
replace description="What is the reference period for data collection?" if Q=="F22_Comments"
replace description="Does the survey collect information on consumption or expenditures?" if Q=="F23_Answer"
replace description="Does the survey collect information on consumption or expenditures?" if Q=="F23_Location"
replace description="Does the survey collect information on consumption or expenditures?" if Q=="F23_Comments"
replace description="Does the survey collect data on quantities?" if Q=="F24_Answer"
replace description="Does the survey collect data on quantities?" if Q=="F24_Location"
replace description="Does the survey collect data on quantities?" if Q=="F24_Comments"
replace description="Does the survey collect data on values?" if Q=="F25_Answer"
replace description="Does the survey collect data on values?" if Q=="F25_Location"
replace description="Does the survey collect data on values?" if Q=="F25_Comments"
replace description="Total number of non-food items " if Q=="N00_Answer"
replace description="Total number of non-food items " if Q=="N00_Location"
replace description="Total number of non-food items " if Q=="N00_Comments"
replace description="What is the reference period for data collection?" if Q=="N01_Answer"
replace description="What is the reference period for data collection?" if Q=="N01_Location"
replace description="What is the reference period for data collection?" if Q=="N01_Comments"
replace description="Does the survey collect data on quantities?" if Q=="N02_Answer"
replace description="Does the survey collect data on quantities?" if Q=="N02_Location"
replace description="Does the survey collect data on quantities?" if Q=="N02_Comments"
replace description="Does the survey collect data on values?" if Q=="N03_Answer"
replace description="Does the survey collect data on values?" if Q=="N03_Location"
replace description="Does the survey collect data on values?" if Q=="N03_Comments"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N04_Answer"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N04_Location"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N04_Comments"
replace description="What is the reference period for data collection?" if Q=="N05_Answer"
replace description="What is the reference period for data collection?" if Q=="N05_Location"
replace description="What is the reference period for data collection?" if Q=="N05_Comments"
replace description="Does the survey collect data on quantities?" if Q=="N06_Answer"
replace description="Does the survey collect data on quantities?" if Q=="N06_Location"
replace description="Does the survey collect data on quantities?" if Q=="N06_Comments"
replace description="Does the survey collect data on values?" if Q=="N07_Answer"
replace description="Does the survey collect data on values?" if Q=="N07_Location"
replace description="Does the survey collect data on values?" if Q=="N07_Comments"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N08_Answer"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N08_Location"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N08_Comments"
replace description="What is the reference period for data collection?" if Q=="N09_Answer"
replace description="What is the reference period for data collection?" if Q=="N09_Location"
replace description="What is the reference period for data collection?" if Q=="N09_Comments"
replace description="Does the survey collect data on quantities?" if Q=="N10_Answer"
replace description="Does the survey collect data on quantities?" if Q=="N10_Location"
replace description="Does the survey collect data on quantities?" if Q=="N10_Comments"
replace description="Does the survey collect data on values?" if Q=="N11_Answer"
replace description="Does the survey collect data on values?" if Q=="N11_Location"
replace description="Does the survey collect data on values?" if Q=="N11_Comments"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N12_Answer"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N12_Location"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N12_Comments"
replace description="What is the reference period for data collection?" if Q=="N13_Answer"
replace description="What is the reference period for data collection?" if Q=="N13_Location"
replace description="What is the reference period for data collection?" if Q=="N13_Comments"
replace description="Does the survey collect data on quantities?" if Q=="N14_Answer"
replace description="Does the survey collect data on quantities?" if Q=="N14_Location"
replace description="Does the survey collect data on quantities?" if Q=="N14_Comments"
replace description="Does the survey collect data on values?" if Q=="N15_Answer"
replace description="Does the survey collect data on values?" if Q=="N15_Location"
replace description="Does the survey collect data on values?" if Q=="N15_Comments"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N16_Answer"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N16_Location"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N16_Comments"
replace description="What is the reference period for data collection?" if Q=="N17_Answer"
replace description="What is the reference period for data collection?" if Q=="N17_Location"
replace description="What is the reference period for data collection?" if Q=="N17_Comments"
replace description="Does the survey collect data on quantities?" if Q=="N18_Answer"
replace description="Does the survey collect data on quantities?" if Q=="N18_Location"
replace description="Does the survey collect data on quantities?" if Q=="N18_Comments"
replace description="Does the survey collect data on values?" if Q=="N19_Answer"
replace description="Does the survey collect data on values?" if Q=="N19_Location"
replace description="Does the survey collect data on values?" if Q=="N19_Comments"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N20_Answer"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N20_Location"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N20_Comments"
replace description="What is the reference period for data collection?" if Q=="N21_Answer"
replace description="What is the reference period for data collection?" if Q=="N21_Location"
replace description="What is the reference period for data collection?" if Q=="N21_Comments"
replace description="Does the survey collect data on quantities?" if Q=="N22_Answer"
replace description="Does the survey collect data on quantities?" if Q=="N22_Location"
replace description="Does the survey collect data on quantities?" if Q=="N22_Comments"
replace description="Does the survey collect data on values?" if Q=="N23_Answer"
replace description="Does the survey collect data on values?" if Q=="N23_Location"
replace description="Does the survey collect data on values?" if Q=="N23_Comments"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N24_Answer"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N24_Location"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N24_Comments"
replace description="What is the reference period for data collection?" if Q=="N25_Answer"
replace description="What is the reference period for data collection?" if Q=="N25_Location"
replace description="What is the reference period for data collection?" if Q=="N25_Comments"
replace description="Does the survey collect data on quantities?" if Q=="N26_Answer"
replace description="Does the survey collect data on quantities?" if Q=="N26_Location"
replace description="Does the survey collect data on quantities?" if Q=="N26_Comments"
replace description="Does the survey collect data on values?" if Q=="N27_Answer"
replace description="Does the survey collect data on values?" if Q=="N27_Location"
replace description="Does the survey collect data on values?" if Q=="N27_Comments"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N28_Answer"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N28_Location"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N28_Comments"
replace description="What is the reference period for data collection?" if Q=="N29_Answer"
replace description="What is the reference period for data collection?" if Q=="N29_Location"
replace description="What is the reference period for data collection?" if Q=="N29_Comments"
replace description="Does the survey collect data on quantities?" if Q=="N30_Answer"
replace description="Does the survey collect data on quantities?" if Q=="N30_Location"
replace description="Does the survey collect data on quantities?" if Q=="N30_Comments"
replace description="Does the survey collect data on values?" if Q=="N31_Answer"
replace description="Does the survey collect data on values?" if Q=="N31_Location"
replace description="Does the survey collect data on values?" if Q=="N31_Comments"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N32_Answer"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N32_Location"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N32_Comments"
replace description="What is the reference period for data collection?" if Q=="N33_Answer"
replace description="What is the reference period for data collection?" if Q=="N33_Location"
replace description="What is the reference period for data collection?" if Q=="N33_Comments"
replace description="Does the survey collect data on quantities?" if Q=="N34_Answer"
replace description="Does the survey collect data on quantities?" if Q=="N34_Location"
replace description="Does the survey collect data on quantities?" if Q=="N34_Comments"
replace description="Does the survey collect data on values?" if Q=="N35_Answer"
replace description="Does the survey collect data on values?" if Q=="N35_Location"
replace description="Does the survey collect data on values?" if Q=="N35_Comments"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N36_Answer"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N36_Location"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N36_Comments"
replace description="What is the reference period for data collection?" if Q=="N37_Answer"
replace description="What is the reference period for data collection?" if Q=="N37_Location"
replace description="What is the reference period for data collection?" if Q=="N37_Comments"
replace description="Does the survey collect data on quantities?" if Q=="N38_Answer"
replace description="Does the survey collect data on quantities?" if Q=="N38_Location"
replace description="Does the survey collect data on quantities?" if Q=="N38_Comments"
replace description="Does the survey collect data on values?" if Q=="N39_Answer"
replace description="Does the survey collect data on values?" if Q=="N39_Location"
replace description="Does the survey collect data on values?" if Q=="N39_Comments"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N40_Answer"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N40_Location"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N40_Comments"
replace description="What is the reference period for data collection?" if Q=="N41_Answer"
replace description="What is the reference period for data collection?" if Q=="N41_Location"
replace description="What is the reference period for data collection?" if Q=="N41_Comments"
replace description="Does the survey collect data on quantities?" if Q=="N42_Answer"
replace description="Does the survey collect data on quantities?" if Q=="N42_Location"
replace description="Does the survey collect data on quantities?" if Q=="N42_Comments"
replace description="Does the survey collect data on values?" if Q=="N43_Answer"
replace description="Does the survey collect data on values?" if Q=="N43_Location"
replace description="Does the survey collect data on values?" if Q=="N43_Comments"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N44_Answer"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N44_Location"
replace description="Is there information on in-kind transfers to/from the household?" if Q=="N44_Comments"
replace description="Total number of durable items " if Q=="D01_Answer"
replace description="Total number of durable items " if Q=="D01_Location"
replace description="Total number of durable items " if Q=="D01_Comments"
replace description="Does the survey collect data on quantities for durables?" if Q=="D02_Answer"
replace description="Does the survey collect data on quantities for durables?" if Q=="D02_Location"
replace description="Does the survey collect data on quantities for durables?" if Q=="D02_Comments"
replace description="Does the survey collect data on values for durables?" if Q=="D03_Answer"
replace description="Does the survey collect data on values for durables?" if Q=="D03_Location"
replace description="Does the survey collect data on values for durables?" if Q=="D03_Comments"
replace description="What is the number of a certain type that the survey collects information for?" if Q=="D04_Answer"
replace description="What is the number of a certain type that the survey collects information for?" if Q=="D04_Location"
replace description="What is the number of a certain type that the survey collects information for?" if Q=="D04_Comments"
replace description="Is there information about the year of purchase/acquisition of durable goods?" if Q=="D05_Answer"
replace description="Is there information about the year of purchase/acquisition of durable goods?" if Q=="D05_Location"
replace description="Is there information about the year of purchase/acquisition of durable goods?" if Q=="D05_Comments"
replace description="Is there information about the value of durable goods at purchase?" if Q=="D06_Answer"
replace description="Is there information about the value of durable goods at purchase?" if Q=="D06_Location"
replace description="Is there information about the value of durable goods at purchase?" if Q=="D06_Comments"
replace description="Is there information about the current value of the good?" if Q=="D07_Answer"
replace description="Is there information about the current value of the good?" if Q=="D07_Location"
replace description="Is there information about the current value of the good?" if Q=="D07_Comments"
replace description="Is there information on in-kind transfers of durable goods to the household?" if Q=="D08_Answer"
replace description="Is there information on in-kind transfers of durable goods to the household?" if Q=="D08_Location"
replace description="Is there information on in-kind transfers of durable goods to the household?" if Q=="D08_Comments"
replace description="Type of dwellling (house, apartment, etc.)" if Q=="H01_Answer"
replace description="Type of dwellling (house, apartment, etc.)" if Q=="H01_Location"
replace description="Type of dwellling (house, apartment, etc.)" if Q=="H01_Comments"
replace description="Area of the dwelling" if Q=="H02_Answer"
replace description="Area of the dwelling" if Q=="H02_Location"
replace description="Area of the dwelling" if Q=="H02_Comments"
replace description="Number of bedrooms" if Q=="H03_Answer"
replace description="Number of bedrooms" if Q=="H03_Location"
replace description="Number of bedrooms" if Q=="H03_Comments"
replace description="Kitchen" if Q=="H04_Answer"
replace description="Kitchen" if Q=="H04_Location"
replace description="Kitchen" if Q=="H04_Comments"
replace description="Number of bathrooms" if Q=="H05_Answer"
replace description="Number of bathrooms" if Q=="H05_Location"
replace description="Number of bathrooms" if Q=="H05_Comments"
replace description="Material of the walls" if Q=="H06_Answer"
replace description="Material of the walls" if Q=="H06_Location"
replace description="Material of the walls" if Q=="H06_Comments"
replace description="Material of the roof" if Q=="H07_Answer"
replace description="Material of the roof" if Q=="H07_Location"
replace description="Material of the roof" if Q=="H07_Comments"
replace description="Material of the floor" if Q=="H08_Answer"
replace description="Material of the floor" if Q=="H08_Location"
replace description="Material of the floor" if Q=="H08_Comments"
replace description="Garage" if Q=="H09_Answer"
replace description="Garage" if Q=="H09_Location"
replace description="Garage" if Q=="H09_Comments"
replace description="Access to public transportation" if Q=="H10_Answer"
replace description="Access to public transportation" if Q=="H10_Location"
replace description="Access to public transportation" if Q=="H10_Comments"
replace description="Others (specify in comments)" if Q=="H11_Answer"
replace description="Others (specify in comments)" if Q=="H11_Location"
replace description="Others (specify in comments)" if Q=="H11_Comments"
replace description="Electricity (list categories in comments)" if Q=="H12_Answer"
replace description="Electricity (list categories in comments)" if Q=="H12_Location"
replace description="Electricity (list categories in comments)" if Q=="H12_Comments"
replace description="Sanitation (list categories in comments)" if Q=="H13_Answer"
replace description="Sanitation (list categories in comments)" if Q=="H13_Location"
replace description="Sanitation (list categories in comments)" if Q=="H13_Comments"
replace description="Water (list categories in comments)" if Q=="H14_Answer"
replace description="Water (list categories in comments)" if Q=="H14_Location"
replace description="Water (list categories in comments)" if Q=="H14_Comments"
replace description="Other services, e.g. internet, garbage collection, etc. (list in comments)" if Q=="H15_Answer"
replace description="Other services, e.g. internet, garbage collection, etc. (list in comments)" if Q=="H15_Location"
replace description="Other services, e.g. internet, garbage collection, etc. (list in comments)" if Q=="H15_Comments"
replace description="Is there information on the amount of rent paid?" if Q=="H16_Answer"
replace description="Is there information on the amount of rent paid?" if Q=="H16_Location"
replace description="Is there information on the amount of rent paid?" if Q=="H16_Comments"
replace description="What is the reference period for data collection?" if Q=="H17_Answer"
replace description="What is the reference period for data collection?" if Q=="H17_Location"
replace description="What is the reference period for data collection?" if Q=="H17_Comments"
replace description="Does the amount of rent paid includes utilities?" if Q=="H18_Answer"
replace description="Does the amount of rent paid includes utilities?" if Q=="H18_Location"
replace description="Does the amount of rent paid includes utilities?" if Q=="H18_Comments"
replace description="Is there information about subsidized housing?" if Q=="H19_Answer"
replace description="Is there information about subsidized housing?" if Q=="H19_Location"
replace description="Is there information about subsidized housing?" if Q=="H19_Comments"
replace description="What is the reference period for data collection?" if Q=="H20_Answer"
replace description="What is the reference period for data collection?" if Q=="H20_Location"
replace description="What is the reference period for data collection?" if Q=="H20_Comments"
replace description="Is there information on self-reported rent (write down the question in comments)?" if Q=="H21_Answer"
replace description="Is there information on self-reported rent (write down the question in comments)?" if Q=="H21_Location"
replace description="Is there information on self-reported rent (write down the question in comments)?" if Q=="H21_Comments"
replace description="What is the reference period for data collection?" if Q=="H22_Answer"
replace description="What is the reference period for data collection?" if Q=="H22_Location"
replace description="What is the reference period for data collection?" if Q=="H22_Comments"
replace description="Is there information mortgage payments?" if Q=="H23_Answer"
replace description="Is there information mortgage payments?" if Q=="H23_Location"
replace description="Is there information mortgage payments?" if Q=="H23_Comments"
replace description="What is the reference period for data collection?" if Q=="H24_Answer"
replace description="What is the reference period for data collection?" if Q=="H24_Location"
replace description="What is the reference period for data collection?" if Q=="H24_Comments"
replace description="Is there information on imputed rents?  (If yes, describe in comments the method used)" if Q=="H25_Answer"
replace description="Is there information on imputed rents?  (If yes, describe in comments the method used)" if Q=="H25_Location"
replace description="Is there information on imputed rents?  (If yes, describe in comments the method used)" if Q=="H25_Comments"
replace description="1.1 Food" if Q=="C01_Answer"
replace description="1.1 Food" if Q=="C01_Location"
replace description="1.1 Food" if Q=="C01_Comments"
replace description="1.2 Non-alcoholic beverages" if Q=="C02_Answer"
replace description="1.2 Non-alcoholic beverages" if Q=="C02_Location"
replace description="1.2 Non-alcoholic beverages" if Q=="C02_Comments"
replace description="2.1 Alcoholic beverages" if Q=="C03_Answer"
replace description="2.1 Alcoholic beverages" if Q=="C03_Location"
replace description="2.1 Alcoholic beverages" if Q=="C03_Comments"
replace description="2.2 Tobacco" if Q=="C04_Answer"
replace description="2.2 Tobacco" if Q=="C04_Location"
replace description="2.2 Tobacco" if Q=="C04_Comments"
replace description="2.3 Narcotics" if Q=="C05_Answer"
replace description="2.3 Narcotics" if Q=="C05_Location"
replace description="2.3 Narcotics" if Q=="C05_Comments"
replace description="3.1 Clothing" if Q=="C06_Answer"
replace description="3.1 Clothing" if Q=="C06_Location"
replace description="3.1 Clothing" if Q=="C06_Comments"
replace description="3.2 Footwear" if Q=="C07_Answer"
replace description="3.2 Footwear" if Q=="C07_Location"
replace description="3.2 Footwear" if Q=="C07_Comments"
replace description="4.1 Actual rentals for housing" if Q=="C08_Answer"
replace description="4.1 Actual rentals for housing" if Q=="C08_Location"
replace description="4.1 Actual rentals for housing" if Q=="C08_Comments"
replace description="4.2 Imputed rentals for housing" if Q=="C09_Answer"
replace description="4.2 Imputed rentals for housing" if Q=="C09_Location"
replace description="4.2 Imputed rentals for housing" if Q=="C09_Comments"
replace description="4.3 Maintenance and repair of the dwelling" if Q=="C10_Answer"
replace description="4.3 Maintenance and repair of the dwelling" if Q=="C10_Location"
replace description="4.3 Maintenance and repair of the dwelling" if Q=="C10_Comments"
replace description="4.4 Water supply and miscellaneous services relating to the dwelling" if Q=="C11_Answer"
replace description="4.4 Water supply and miscellaneous services relating to the dwelling" if Q=="C11_Location"
replace description="4.4 Water supply and miscellaneous services relating to the dwelling" if Q=="C11_Comments"
replace description="4.5 Electricity, gas and other fuels" if Q=="C12_Answer"
replace description="4.5 Electricity, gas and other fuels" if Q=="C12_Location"
replace description="4.5 Electricity, gas and other fuels" if Q=="C12_Comments"
replace description="5.1 Furniture and furnishings, carpets and other floor coverings" if Q=="C13_Answer"
replace description="5.1 Furniture and furnishings, carpets and other floor coverings" if Q=="C13_Location"
replace description="5.1 Furniture and furnishings, carpets and other floor coverings" if Q=="C13_Comments"
replace description="5.2 Household textiles" if Q=="C14_Answer"
replace description="5.2 Household textiles" if Q=="C14_Location"
replace description="5.2 Household textiles" if Q=="C14_Comments"
replace description="5.3 Household appliances" if Q=="C15_Answer"
replace description="5.3 Household appliances" if Q=="C15_Location"
replace description="5.3 Household appliances" if Q=="C15_Comments"
replace description="5.4 Glassware, tableware and household utensils" if Q=="C16_Answer"
replace description="5.4 Glassware, tableware and household utensils" if Q=="C16_Location"
replace description="5.4 Glassware, tableware and household utensils" if Q=="C16_Comments"
replace description="5.5 Tools and equipment for house and garden" if Q=="C17_Answer"
replace description="5.5 Tools and equipment for house and garden" if Q=="C17_Location"
replace description="5.5 Tools and equipment for house and garden" if Q=="C17_Comments"
replace description="5.6 Goods and services for routine household maintenance" if Q=="C18_Answer"
replace description="5.6 Goods and services for routine household maintenance" if Q=="C18_Location"
replace description="5.6 Goods and services for routine household maintenance" if Q=="C18_Comments"
replace description="6.1 Medical products, appliances and equipment" if Q=="C19_Answer"
replace description="6.1 Medical products, appliances and equipment" if Q=="C19_Location"
replace description="6.1 Medical products, appliances and equipment" if Q=="C19_Comments"
replace description="6.2 Outpatient services" if Q=="C20_Answer"
replace description="6.2 Outpatient services" if Q=="C20_Location"
replace description="6.2 Outpatient services" if Q=="C20_Comments"
replace description="6.3 Hospital services" if Q=="C21_Answer"
replace description="6.3 Hospital services" if Q=="C21_Location"
replace description="6.3 Hospital services" if Q=="C21_Comments"
replace description="7.1 Purchase of vehicles" if Q=="C22_Answer"
replace description="7.1 Purchase of vehicles" if Q=="C22_Location"
replace description="7.1 Purchase of vehicles" if Q=="C22_Comments"
replace description="7.2 Operation of personal transport equipment" if Q=="C23_Answer"
replace description="7.2 Operation of personal transport equipment" if Q=="C23_Location"
replace description="7.2 Operation of personal transport equipment" if Q=="C23_Comments"
replace description="7.3 Transport services" if Q=="C24_Answer"
replace description="7.3 Transport services" if Q=="C24_Location"
replace description="7.3 Transport services" if Q=="C24_Comments"
replace description="8.1 Postal services" if Q=="C25_Answer"
replace description="8.1 Postal services" if Q=="C25_Location"
replace description="8.1 Postal services" if Q=="C25_Comments"
replace description="8.2 Telephone and telefax equipment" if Q=="C26_Answer"
replace description="8.2 Telephone and telefax equipment" if Q=="C26_Location"
replace description="8.2 Telephone and telefax equipment" if Q=="C26_Comments"
replace description="8.3 Telephone and telefax services" if Q=="C27_Answer"
replace description="8.3 Telephone and telefax services" if Q=="C27_Location"
replace description="8.3 Telephone and telefax services" if Q=="C27_Comments"
replace description="9.1 Audio-visual, photographic and information processing equipment" if Q=="C28_Answer"
replace description="9.1 Audio-visual, photographic and information processing equipment" if Q=="C28_Location"
replace description="9.1 Audio-visual, photographic and information processing equipment" if Q=="C28_Comments"
replace description="9.2 Other major durables for recreation and culture" if Q=="C29_Answer"
replace description="9.2 Other major durables for recreation and culture" if Q=="C29_Location"
replace description="9.2 Other major durables for recreation and culture" if Q=="C29_Comments"
replace description="9.3 Other recreational items and equipment, gardens and pets" if Q=="C30_Answer"
replace description="9.3 Other recreational items and equipment, gardens and pets" if Q=="C30_Location"
replace description="9.3 Other recreational items and equipment, gardens and pets" if Q=="C30_Comments"
replace description="9.4 Recreational and cultural services" if Q=="C31_Answer"
replace description="9.4 Recreational and cultural services" if Q=="C31_Location"
replace description="9.4 Recreational and cultural services" if Q=="C31_Comments"
replace description="9.5 Newspapers, books and stationery" if Q=="C32_Answer"
replace description="9.5 Newspapers, books and stationery" if Q=="C32_Location"
replace description="9.5 Newspapers, books and stationery" if Q=="C32_Comments"
replace description="9.6 Package holidays" if Q=="C33_Answer"
replace description="9.6 Package holidays" if Q=="C33_Location"
replace description="9.6 Package holidays" if Q=="C33_Comments"
replace description="10.1 Pre-primary and primary education" if Q=="C34_Answer"
replace description="10.1 Pre-primary and primary education" if Q=="C34_Location"
replace description="10.1 Pre-primary and primary education" if Q=="C34_Comments"
replace description="10.2 Secondary education" if Q=="C35_Answer"
replace description="10.2 Secondary education" if Q=="C35_Location"
replace description="10.2 Secondary education" if Q=="C35_Comments"
replace description="10.3 Post-secondary non-tertiary education" if Q=="C36_Answer"
replace description="10.3 Post-secondary non-tertiary education" if Q=="C36_Location"
replace description="10.3 Post-secondary non-tertiary education" if Q=="C36_Comments"
replace description="10.4 Tertiary education" if Q=="C37_Answer"
replace description="10.4 Tertiary education" if Q=="C37_Location"
replace description="10.4 Tertiary education" if Q=="C37_Comments"
replace description="10.5 Education not definable by level" if Q=="C38_Answer"
replace description="10.5 Education not definable by level" if Q=="C38_Location"
replace description="10.5 Education not definable by level" if Q=="C38_Comments"
replace description="11.1 Catering services" if Q=="C39_Answer"
replace description="11.1 Catering services" if Q=="C39_Location"
replace description="11.1 Catering services" if Q=="C39_Comments"
replace description="11.2 Accommodation services" if Q=="C40_Answer"
replace description="11.2 Accommodation services" if Q=="C40_Location"
replace description="11.2 Accommodation services" if Q=="C40_Comments"
replace description="12.1 Personal care" if Q=="C41_Answer"
replace description="12.1 Personal care" if Q=="C41_Location"
replace description="12.1 Personal care" if Q=="C41_Comments"
replace description="12.2 Prostitution" if Q=="C42_Answer"
replace description="12.2 Prostitution" if Q=="C42_Location"
replace description="12.2 Prostitution" if Q=="C42_Comments"
replace description="12.3 Personal effects n.e.c." if Q=="C43_Answer"
replace description="12.3 Personal effects n.e.c." if Q=="C43_Location"
replace description="12.3 Personal effects n.e.c." if Q=="C43_Comments"
replace description="12.4 Social protection" if Q=="C44_Answer"
replace description="12.4 Social protection" if Q=="C44_Location"
replace description="12.4 Social protection" if Q=="C44_Comments"
replace description="12.5 Insurance" if Q=="C45_Answer"
replace description="12.5 Insurance" if Q=="C45_Location"
replace description="12.5 Insurance" if Q=="C45_Comments"
replace description="12.6 Financial services n.e.c." if Q=="C46_Answer"
replace description="12.6 Financial services n.e.c." if Q=="C46_Location"
replace description="12.6 Financial services n.e.c." if Q=="C46_Comments"
replace description="12.7 Other services n.e.c." if Q=="C47_Answer"
replace description="12.7 Other services n.e.c." if Q=="C47_Location"
replace description="12.7 Other services n.e.c." if Q=="C47_Comments"


*----------------------Major categories---------------------------------
gen question_category=""

local yes_no_na Q_1_a Q_1_b Q_1_c Q_1_d Q_1_e Q_6 Q_11_d Q_11_e Q_12_d Q_12_e Q_13_e Q_13_f Q_14_c ///
 Q_14_d Q_15_c Q_15_d Q_17_b Q_17_c Q_17_d Q_18_b Q_18_c Q_18_d Q_19_b Q_19_c Q_19_d ///
 Q_20_b Q_20_c Q_20_d Q_21_b Q_21_c Q_21_d Q_22_b Q_22_c Q_22_d Q_23_b Q_23_c Q_23_d ///
 Q_24_b Q_24_c Q_24_d Q_25_b Q_25_c Q_25_d Q_26_b Q_26_c Q_26_d Q_27_b Q_27_c Q_27_d ///
 Q_29 Q_30 Q_31 Q_32 Q_33 Q_34 Q_35 Q_36_a Q_37 Q_38_a Q_39_a Q_40_a Q_41_a Q_41_b /// 
 Q_41_c Q_41_d Q_41_e Q_41_f Q_41_g Q_41_h Q_41_i Q_41_j Q_41_k Q_42_a Q_42_b Q_42_c ///
 Q_42_d Q_43 Q_44_a Q_44_b Q_44_c Q_44_d Q_44_e Q_44_f Q_44_g Q_44_h Q_44_i Q_44_j ///
 Q_44_k Q_44_l Q_44_m Q_44_n Q_44_o Q_44_p Q_44_q Q_44_r Q_44_s Q_44_t Q_44_u Q_44_v ///
 Q_44_w Q_44_x Q_44_y Q_44_z Q_44_aa Q_44_ab Q_44_ac Q_44_ad Q_44_ae Q_44_af Q_44_ag ///
 Q_44_ah Q_44_ai Q_44_aj Q_44_ak Q_44_al Q_44_am Q_44_an Q_44_ao Q_44_ap Q_44_aq ///
 Q_44_ar Q_44_as Q_44_at Q_44_au
 foreach i of local yes_no_na {
	replace question_category="Yes/no/na" if Q=="`i'"
}

local time_periods Q_11_b Q_12_b Q_13_c Q_14_b Q_15_b  Q_17_a Q_18_a Q_19_a Q_20_a ///
 Q_21_a Q_22_a Q_23_a Q_24_a Q_25_a Q_26_a Q_27_a Q_36_b  Q_38_b Q_39_b Q_40_b
  foreach i of local time_periods {
	replace question_category="Time period" if Q=="`i'"
}

replace question_category="Other" if question_category==""

*replace Response="No" if Response=="no"
 
*----------------------Generate Category Variable---------------------------------
gen Category=substr(Q,1,1)
replace Category="Main" if Category=="Q"
replace Category="Sampling Frame" if Category=="S"
replace Category="Food" if Category=="F"
replace Category="Non Food" if Category=="N"
replace Category="Durables" if Category=="D"
replace Category="Housing" if Category=="H"
replace Category="COICOP" if Category=="C"

split Q, parse(_)
drop Q
rename Q1 Question
rename Q2 Type

reshape wide Response, i(region country year country_year survey_name user last_survey Question) j(Type) string
rename ResponseAnswer Answer 
rename ResponseComments Comments
rename ResponseLocation Location

gen Subcategory=""
replace Subcategory="Food at home" if Question=="F01"
replace Subcategory="Food at home" if Question=="F02"
replace Subcategory="Food at home" if Question=="F03"
replace Subcategory="Food at home" if Question=="F04"
replace Subcategory="Food at home" if Question=="F05"
replace Subcategory="Food outside home" if Question=="F06"
replace Subcategory="Food outside home" if Question=="F07"
replace Subcategory="Food outside home" if Question=="F08"
replace Subcategory="Food outside home" if Question=="F09"
replace Subcategory="Food outside home" if Question=="F10"
replace Subcategory="Food produced at home" if Question=="F11"
replace Subcategory="Food produced at home" if Question=="F12"
replace Subcategory="Food produced at home" if Question=="F13"
replace Subcategory="Food produced at home" if Question=="F14"
replace Subcategory="Food produced at home" if Question=="F15"
replace Subcategory="In-kind transfers to the household" if Question=="F16"
replace Subcategory="In-kind transfers to the household" if Question=="F17"
replace Subcategory="In-kind transfers to the household" if Question=="F18"
replace Subcategory="In-kind transfers to the household" if Question=="F19"
replace Subcategory="In-kind transfers to the household" if Question=="F20"
replace Subcategory="In-kind transfers to other households" if Question=="F21"
replace Subcategory="In-kind transfers to other households" if Question=="F22"
replace Subcategory="In-kind transfers to other households" if Question=="F23"
replace Subcategory="In-kind transfers to other households" if Question=="F24"
replace Subcategory="In-kind transfers to other households" if Question=="F25"
replace Subcategory="Number of items" if Question=="N00"
replace Subcategory="Alcoholic beverages, tobacco and narcotics" if Question=="N01"
replace Subcategory="Alcoholic beverages, tobacco and narcotics" if Question=="N02"
replace Subcategory="Alcoholic beverages, tobacco and narcotics" if Question=="N03"
replace Subcategory="Alcoholic beverages, tobacco and narcotics" if Question=="N04"
replace Subcategory="Clothing and footwear" if Question=="N05"
replace Subcategory="Clothing and footwear" if Question=="N06"
replace Subcategory="Clothing and footwear" if Question=="N07"
replace Subcategory="Clothing and footwear" if Question=="N08"
replace Subcategory="Housing, water, electricity, gas and other fuels" if Question=="N09"
replace Subcategory="Housing, water, electricity, gas and other fuels" if Question=="N10"
replace Subcategory="Housing, water, electricity, gas and other fuels" if Question=="N11"
replace Subcategory="Housing, water, electricity, gas and other fuels" if Question=="N12"
replace Subcategory="Furnishings, household equipment and routine household maintenance" if Question=="N13"
replace Subcategory="Furnishings, household equipment and routine household maintenance" if Question=="N14"
replace Subcategory="Furnishings, household equipment and routine household maintenance" if Question=="N15"
replace Subcategory="Furnishings, household equipment and routine household maintenance" if Question=="N16"
replace Subcategory="Health" if Question=="N17"
replace Subcategory="Health" if Question=="N18"
replace Subcategory="Health" if Question=="N19"
replace Subcategory="Health" if Question=="N20"
replace Subcategory="Transport" if Question=="N21"
replace Subcategory="Transport" if Question=="N22"
replace Subcategory="Transport" if Question=="N23"
replace Subcategory="Transport" if Question=="N24"
replace Subcategory="Communication" if Question=="N25"
replace Subcategory="Communication" if Question=="N26"
replace Subcategory="Communication" if Question=="N27"
replace Subcategory="Communication" if Question=="N28"
replace Subcategory="Recreation and culture" if Question=="N29"
replace Subcategory="Recreation and culture" if Question=="N30"
replace Subcategory="Recreation and culture" if Question=="N31"
replace Subcategory="Recreation and culture" if Question=="N32"
replace Subcategory="Education" if Question=="N33"
replace Subcategory="Education" if Question=="N34"
replace Subcategory="Education" if Question=="N35"
replace Subcategory="Education" if Question=="N36"
replace Subcategory="Restaurants and hotels" if Question=="N37"
replace Subcategory="Restaurants and hotels" if Question=="N38"
replace Subcategory="Restaurants and hotels" if Question=="N39"
replace Subcategory="Restaurants and hotels" if Question=="N40"
replace Subcategory="Miscellaneous goods and services" if Question=="N41"
replace Subcategory="Miscellaneous goods and services" if Question=="N42"
replace Subcategory="Miscellaneous goods and services" if Question=="N43"
replace Subcategory="Miscellaneous goods and services" if Question=="N44"



*---------------------------Categorize types of responses:------------------------------

*Yes/No/n.a
gen R_Yes_No=""
replace R_Yes_No=Answer if Answer=="Yes"
replace R_Yes_No=Answer if Answer=="No"
replace Answer="n/a" if Answer=="NA" | Answer=="Not available" | Answer=="n.a."
replace R_Yes_No=Answer if Answer=="n/a"

*Time Periods
gen R_Time_Periods=""
replace R_Time_Periods=Answer if Answer=="1 week/7-day diary"
replace R_Time_Periods=Answer if Answer=="2 weeks/14-day diary"
replace R_Time_Periods=Answer if Answer=="1-month"
replace R_Time_Periods=Answer if Answer=="2 months"
replace R_Time_Periods=Answer if Answer=="3-4 months"
replace R_Time_Periods=Answer if Answer=="5-6 months"
replace R_Time_Periods=Answer if Answer=="More than 6 months"
replace R_Time_Periods=Answer if Answer=="Other (specify in comments)"
replace R_Time_Periods=Answer if Answer=="n/a"
replace R_Time_Periods=Answer if Answer=="Year-long"
replace R_Time_Periods=Answer if Answer=="Quarter-long (specify in comments)"


*Categorical responses
cap gen R_Categories=""
replace R_Categories=Answer if Answer=="Individual"
replace R_Categories=Answer if Answer=="Household"
replace R_Categories=Answer if Answer=="Other (specify in comments)"
replace R_Categories=Answer if Answer=="Quantities"
replace R_Categories=Answer if Answer=="Pecuniary values"
replace R_Categories=Answer if Answer=="Both quantities and pecuniary"
replace R_Categories=Answer if Answer=="None"
replace R_Categories=Answer if Answer=="Diary"
replace R_Categories=Answer if Answer=="Recall"
replace R_Categories=Answer if Answer=="n/a"
replace R_Categories=Answer if Answer=="Consumption"
replace R_Categories=Answer if Answer=="Expenditure"
replace R_Categories=Answer if Answer=="Both"
replace R_Categories=Answer if Answer=="Other (specify in comments)"
replace R_Categories=Answer if Answer=="n/a"
replace R_Categories=Answer if Answer=="Consumption/expenditures  module"
replace R_Categories=Answer if Answer=="Agricultural production module"
replace R_Categories=Answer if Answer=="Other (specify in comments)"
replace R_Categories=Answer if Answer=="Direct"
replace R_Categories=Answer if Answer=="Ideal"
replace R_Categories=Answer if Answer=="Other (specify in comments)"


*Filter 
gen filter1=(Category=="sampling frame") if Category!="" //para que missing values no se conviertan en 0
gen filter2=(R_Yes_No==Answer | R_Time_Periods==Answer | R_Categories==Answer)
gen filter3=(Answer=="")
gen count=1


d

export excel using "metadata_long.xls", firstrow(varl) replace



end metaform


